#!/usr/bin/env node
/* ==========================================================================
   Bluebird Wellness: menu generator

   Reads the clinic's menu, data/drips.json, and writes:
     data/menu.js                  window.MENU (the JSON as it is) and the
                                   picture/tint/badge of every drip, for the
                                   home page (script.js)
     data/book-list.js             window.BOOK_LIST: the treatments and
                                   prices the booking preview (booking.js)
                                   offers, on every page
     treatments/<slug>/index.html  one static page per drip, with all its
                                   text in the HTML
     privacy/, terms/, cancellations/, cookies/, accessibility/
                                   the policy pages, from content/legal/
                                   and the business's details in
                                   site-config.js
     ingredients/index.html        the ingredient glossary (the menu's
                                   glossary), with where each one is used
     index.html                    only its Book and contact links (from
                                   site-config.js) and the inlined logo
     data/menu-check.txt           the check report (also printed)

   Run it after editing data/drips.json, site-config.js (the booking link
   and contact details), the logo (images/logo/bluebird-mark.svg), the
   header, menu or footer in index.html, or a treatment's image, alt, tint or
   badge in TREATMENTS (script.js), then commit what it writes:
     node scripts/build-menu.mjs
   To check the files as they are, without writing anything:
     node scripts/build-menu.mjs --check

   Rule zero: every treatment string is shown exactly as it is in
   data/drips.json, escaped as text. Elements that show one carry
   data-verbatim with its path in the JSON (data-verbatim-part="start" marks
   a string's opening sentences only); the check compares each of them
   with the JSON and confirms nothing is missing.
   ========================================================================== */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

/* ---------- Settings ---------- */

// The brand name in page titles, headers and footers (the menu text itself
// stays exactly as written).
const SITE_NAME = 'Bluebird Wellness';

// Every drip's picture is images/treatments/<slug>.webp whenever that file
// exists (a Pro drip with its own file uses it too). Otherwise it is its
// stage treatment's image, or its standard version's.
//
// Drips with no picture on the stage (none at the moment: every drip is a
// TREATMENTS entry or its Pro version). Add one as
//   'slug': { placeholder: { shape: 'drop', colour: '#E8EFFB' }, alt: '' },
// Until images/treatments/<slug>.webp exists it shows a soft placeholder
// shape; when it does, it is used instead (fill in its alt: a plain
// description of the picture, no claims). An alt here also replaces the
// stage treatment's alt, e.g. for a Pro drip whose own picture differs from
// its standard version's.
const NEW_PICTURES = {};

// Ingredient lines that are medicines. A Pro version's "Pro adds" list never
// shows them (a medicine is not an upgrade feature); they are still listed
// with its ingredients. Matched by the start of the line.
const MEDICINES = ['IV anti-inflammatory painkillers', 'IV anti-sickness medication'];

const GENERATED = 'Generated by scripts/build-menu.mjs from data/drips.json. Don\'t edit by hand.';

/* ---------- Files ---------- */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');
const at = (file) => join(ROOT, file);
const read = (file) => readFileSync(at(file), 'utf8');
const write = (file, text) => {
  if (CHECK_ONLY) return;
  mkdirSync(dirname(at(file)), { recursive: true });
  writeFileSync(at(file), text);
};
const fail = (message) => {
  console.error(`\nbuild-menu: ${message}\n`);
  process.exit(1);
};

const notes = [];

/* ---------- The menu ---------- */

const MENU = JSON.parse(read('data/drips.json'));

// The booking link and contact details (site-config.js, shared with script.js).
// FEATURED_IDS: its featured list (the treatments the home page's line draws).
let FEATURED_IDS = [];
const SITE = (() => {
  const window = {};
  try {
    vm.runInNewContext(read('site-config.js'), { window }, { timeout: 1000 });
  } catch (error) {
    fail(`Could not read site-config.js: ${error.message}`);
  }
  const featured = window.SITE && window.SITE.featured;
  if (featured !== undefined && !Array.isArray(featured)) fail('featured in site-config.js must be a list, e.g. [\'iron\', \'nad\'].');
  FEATURED_IDS = (featured || []).map((id) => String(id).trim());
  return Object.fromEntries(Object.entries(window.SITE || {}).filter(([k]) => k !== 'featured').map(([k, v]) => [k, String(v ?? '').trim()]));
})();
// A true/false setting in site-config.js.
const isOn = (key) => SITE[key] === 'true';
const SITE_URL = SITE.siteUrl ? SITE.siteUrl.replace(/\/?$/, '/') : '';
if (SITE_URL && !/^https?:\/\//.test(SITE_URL)) fail('siteUrl in site-config.js must start with https://.');

const DRIPS = MENU.drips;
if (!Array.isArray(DRIPS) || !DRIPS.length) fail('data/drips.json has no drips.');
for (const drip of DRIPS) {
  for (const key of ['slug', 'name', 'priceLabel', 'description', 'ingredients', 'ingredientDescriptions']) {
    if (drip[key] == null) fail(`${drip.slug || '(no slug)'} has no ${key}.`);
  }
}
const bySlug = Object.fromEntries(DRIPS.map((d) => [d.slug, d]));

/* ---------- The stage's visuals (TREATMENTS in script.js) ---------- */

// TREATMENTS is a plain array literal, so it can be read here without
// running the rest of script.js.
function readTreatments() {
  const src = read('script.js');
  const start = src.indexOf('const TREATMENTS = [');
  const end = src.indexOf('\n];', start);
  if (start < 0 || end < 0) fail('Could not find "const TREATMENTS = [ … ];" in script.js.');
  try {
    return vm.runInNewContext(`(${src.slice(src.indexOf('[', start), end + 2)})`, {}, { timeout: 1000 });
  } catch (error) {
    fail(`Could not read TREATMENTS in script.js: ${error.message}`);
  }
}
const TREATMENTS = readTreatments();

// The line drawings (data/line-art.js, made by scripts/line-art/make-line-art.py),
// shown on the treatment pages while site-config.js says pictures: 'lines'.
const LINE_ART = (() => {
  if (!existsSync(at('data/line-art.js'))) return {};
  const window = {};
  vm.runInNewContext(read('data/line-art.js'), { window }, { timeout: 1000 });
  return window.LINE_ART || {};
})();
const USE_LINES = SITE.pictures !== 'photos';

// Width and height of a WebP file, from its header.
function webpSize(file) {
  const b = readFileSync(at(file));
  if (b.toString('ascii', 0, 4) !== 'RIFF' || b.toString('ascii', 8, 12) !== 'WEBP') return null;
  const chunk = b.toString('ascii', 12, 16);
  if (chunk === 'VP8X') return [1 + b.readUIntLE(24, 3), 1 + b.readUIntLE(27, 3)];
  if (chunk === 'VP8 ') return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
  if (chunk === 'VP8L') {
    const n = b.readUInt32LE(21);
    return [1 + (n & 0x3fff), 1 + ((n >> 14) & 0x3fff)];
  }
  return null;
}

function checkedSize(file, declared) {
  if (!existsSync(at(file))) fail(`Missing image: ${file}`);
  const size = webpSize(file);
  if (!size) return declared;
  if (declared && (declared[0] !== size[0] || declared[1] !== size[1])) {
    notes.push(`${file} is ${size[0]} × ${size[1]}, but TREATMENTS says ${declared[0]} × ${declared[1]}; the pages use the file's size.`);
  }
  return size;
}

// The picture, tint and badge of a drip: images/treatments/<slug>.webp if it
// exists, else its own stage treatment's picture, or (for a Pro drip) its
// standard version's; the tint and badge come from the stage treatment. A
// drip with no stage treatment has a new picture or a placeholder.
function visualsFor(drip) {
  const own = TREATMENTS.find((t) => t.menuSlug === drip.slug);
  const stage = own || (drip.baseVariantSlug && TREATMENTS.find((t) => t.menuSlug === drip.baseVariantSlug));
  const extra = NEW_PICTURES[drip.slug];
  const picture = `images/treatments/${drip.slug}.webp`;
  const hasPicture = existsSync(at(picture));
  if (stage) {
    if (!stage.image && !hasPicture) fail(`TREATMENTS entry "${stage.id}" has no image.`);
    const image = hasPicture ? picture : stage.image;
    const same = image === stage.image; // the stage's own image: its size and fit apply
    return {
      image,
      art: LINE_ART[stage.id] ? stage.id : null,
      imageSize: checkedSize(image, same ? stage.imageSize : null),
      imageFit: (same && stage.imageFit) || null,
      alt: extra?.alt || stage.alt || '',
      tint: stage.showcase?.tint || null,
      badge: own?.badge || null,
    };
  }
  if (!extra) fail(`No picture for ${drip.slug}: link it to a TREATMENTS entry (menuSlug) or add it to NEW_PICTURES.`);
  if (hasPicture) {
    if (!extra.alt) notes.push(`${picture} has no alt text yet: add it to NEW_PICTURES in scripts/build-menu.mjs.`);
    return { image: picture, imageSize: checkedSize(picture, null), imageFit: null, alt: extra.alt || '', tint: null, badge: null };
  }
  return { image: null, placeholder: extra.placeholder, tint: null, badge: null };
}

const VISUALS = Object.fromEntries(DRIPS.map((d) => [d.slug, visualsFor(d)]));

for (const id of FEATURED_IDS) {
  if (!TREATMENTS.some((t) => t.id === id)) fail(`featured in site-config.js lists "${id}", which isn't in TREATMENTS (script.js). Use one of: ${TREATMENTS.map((t) => t.id).join(', ')}.`);
}
if (new Set(FEATURED_IDS).size !== FEATURED_IDS.length) fail('featured in site-config.js lists a treatment twice.');

for (const t of TREATMENTS) {
  if (t.menuSlug && !bySlug[t.menuSlug]) fail(`TREATMENTS entry "${t.id}" links to "${t.menuSlug}", which isn't on the menu.`);
  if (t.standalone && !MENU.standalone?.priceTable.rows.some((row) => row[0] === t.standalone.row)) {
    fail(`TREATMENTS entry "${t.id}" links to the standalone row "${t.standalone.row}", which isn't on the menu.`);
  }
  if (t.standalone && !MENU.standalone.ingredientDescriptions.some((d) => d.name === t.standalone.entry)) {
    fail(`TREATMENTS entry "${t.id}" links to the standalone entry "${t.standalone.entry}", which isn't on the menu.`);
  }
}

/* ---------- HTML helpers ---------- */

const esc = (value) =>
  String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);

// data-verbatim: the path of the string in data/drips.json.
const vb = (path) => ` data-verbatim="${esc(path)}"`;

// "\n\n" in a menu string is a paragraph break.
const paras = (text, indent = '') => String(text).split('\n\n').map((p) => `${indent}<p>${esc(p)}</p>`).join('\n');

// An HTML comment can't contain "--".
const commentText = (text) => String(text).replace(/--/g, '- -');

const slugify = (text) => String(text).toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* ---------- Ingredients: matching names ----------
   An ingredient line, its description and its glossary entry are matched by
   the part of each name before the first "(" or ",", ignoring case and an
   "L-" prefix: "Vitamin B1 (25mg)" ↔ "Vitamin B1 (Thiamine)", "L-Lysine
   (1000mg)" ↔ "Lysine". A line in brackets is a note, not an ingredient. */

const nameKey = (text) => String(text).split(/[(,]/)[0].trim().toLowerCase().replace(/\s+/g, ' ').replace(/^l-/, '');
const isNote = (line) => /^\(.*\)$/.test(String(line).trim());
const isMedicine = (line) => MEDICINES.some((m) => String(line).startsWith(m));
const BASE_SOLUTION = nameKey('Electrolyte-Rich Solution');

// The glossary, with an anchor per category and per entry.
const GLOSSARY = (MENU.glossary || []).map((c, ci) => ({
  ...c,
  path: `glossary.${ci}`,
  id: slugify(c.category),
  items: c.items.map((item, ii) => ({ ...item, path: `glossary.${ci}.items.${ii}`, id: slugify(item.name), key: nameKey(item.name) })),
}));
const GLOSSARY_ITEMS = GLOSSARY.flatMap((c) => c.items);
{
  const ids = new Set(['main', 'site-header', 'year', 'glossary-search', 'glossary-entries']);
  for (const id of [...GLOSSARY.flatMap((c) => [c.id, `${c.id}-title`]), ...GLOSSARY_ITEMS.map((i) => i.id)]) {
    if (!id || ids.has(id)) fail(`The glossary anchor "${id}" is empty or used twice: rename the category or entry in data/drips.json.`);
    ids.add(id);
  }
}
const glossaryFor = (name) => GLOSSARY_ITEMS.find((item) => item.key === nameKey(name)) || null;

// A drip's ingredient rows, in the menu's order: each line with its
// description (if any), the lines of the base solution grouped under it, the
// notes, and any description that matched no line (shown at the end).
function ingredientRows(drip) {
  const descs = drip.ingredientDescriptions.map((d, j) => ({ ...d, j, key: nameKey(d.name), used: false }));
  const rows = [];
  const notes = [];
  let group = null;
  drip.ingredients.forEach((line, i) => {
    if (isNote(line)) { notes.push({ line, i }); return; }
    const key = nameKey(line);
    const desc = key ? descs.find((d) => !d.used && d.key === key) : null;
    if (desc) desc.used = true;
    const row = { line, i, desc, children: [] };
    if (!desc && group) { group.children.push(row); return; }
    group = key === BASE_SOLUTION ? row : null;
    rows.push(row);
  });
  return { rows, notes, unmatched: descs.filter((d) => !d.used) };
}

// What a Pro version adds to its standard drip: its lines that the standard
// drip doesn't have, in its own order, leaving out notes and medicines.
function proAdds(base, pro) {
  const have = new Set(base.ingredients);
  const adds = [];
  const medicines = [];
  pro.ingredients.forEach((line, i) => {
    if (have.has(line) || isNote(line)) return;
    (isMedicine(line) ? medicines : adds).push({ line, i });
  });
  return { adds, medicines };
}

/* ---------- Book and contact links, and the logo ----------
   Every link marked data-book goes to SITE.bookingUrl; while that is empty,
   to the booking and contact section (#book), and the ones inside that
   section (data-book="here") are hidden. A link marked data-contact="phone",
   "email", "whatsapp" or "maps" gets its tel:, mailto:, wa.me or map link,
   and is hidden while its value is empty. Links are written as seen from the
   home page; rebase() points them back at it from other pages. */

const contactHref = {
  phone: (v) => `tel:${v.replace(/[^\d+]/g, '')}`,
  email: (v) => `mailto:${v}`,
  whatsapp: (v) => `https://wa.me/${v.replace(/\D/g, '')}`,
  maps: (v) => v,
};
const setLink = (tag, href) => {
  const clean = tag.replace(/\shidden(?=[\s>])/g, '');
  const withHref = / href="/.test(clean) ? clean.replace(/\shref="[^"]*"/, ` href="${esc(href || '#book')}"`) : clean.replace(/^<a\b/, `<a href="${esc(href || '#book')}"`);
  return href ? withHref : withHref.replace(/>$/, ' hidden>');
};
// The business's details in the footer (site-config.js), only what is filled in.
function businessLine() {
  const parts = [];
  if (SITE.legalName) parts.push(esc(SITE.legalName));
  if (SITE.companyNumber) parts.push(`${SITE.registeredIn ? `Registered in ${esc(SITE.registeredIn)}, company` : 'Company'} number ${esc(SITE.companyNumber)}`);
  if (SITE.registeredOffice) parts.push(`Registered office: ${esc(SITE.registeredOffice)}`);
  if (SITE.vatNumber) parts.push(`VAT number ${esc(SITE.vatNumber)}`);
  if (SITE.icoNumber) parts.push(`ICO registration ${esc(SITE.icoNumber)}`);
  if (SITE.cqcNumber) parts.push(`Care Quality Commission ID ${esc(SITE.cqcNumber)}`);
  return parts.join(' · ');
}
const withSite = (html) => html
  .replace(/<p class="contact-item__note" data-callout-fee[^>]*>[\s\S]*?<\/p>/g, () =>
    `<p class="contact-item__note" data-callout-fee${SITE.callOutFee ? '' : ' hidden'}>${SITE.callOutFee ? `Call-out charge: ${esc(SITE.callOutFee)}` : ''}</p>`)
  .replace(/<p class="site-footer__business" data-business[^>]*>[\s\S]*?<\/p>/g, () => {
    const line = businessLine();
    return `<p class="site-footer__business" data-business${line ? '' : ' hidden'}>${line}</p>`;
  })
  .replace(/<a\b[^>]*\sdata-book(?:="([^"]*)")?(?=[\s>])[^>]*>/g, (tag, where) =>
    setLink(tag, SITE.bookingUrl || (where === 'here' ? '' : '#book')))
  .replace(/<a\b[^>]*\sdata-contact="([a-z]+)"[^>]*>/g, (tag, kind) =>
    setLink(tag, SITE[kind === 'maps' ? 'mapsUrl' : kind] ? contactHref[kind](SITE[kind === 'maps' ? 'mapsUrl' : kind]) : ''));

// The logo, inline so it takes the colour of its text (currentColor) and
// stays sharp at every size: every <svg class="brand__mark" data-logo> gets
// the drawing in images/logo/bluebird-mark.svg.
const LOGO = (() => {
  const svg = read('images/logo/bluebird-mark.svg');
  const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1];
  const inner = (svg.match(/<svg\b[^>]*>([\s\S]*)<\/svg>/) || [])[1];
  if (!viewBox || !inner) fail('Could not read images/logo/bluebird-mark.svg.');
  return `<svg class="brand__mark" data-logo viewBox="${viewBox}" fill="currentColor" aria-hidden="true" focusable="false">${inner.trim()}</svg>`;
})();
const withLogo = (html) => html.replace(/<svg class="brand__mark" data-logo[^>]*>[\s\S]*?<\/svg>/g, LOGO);

/* ---------- Studies (content/studies/) ----------
   One HTML file per study: a comment with its title, a short summary (for
   the cards) and its order, then the text, with numbered sources at the end
   (<ol class="sources">, each <li id="source-N">) and citations linking to
   them (<a href="#source-N">). Each becomes studies/<file name>/; the home
   page shows the first few, and the Studies menu lists them all. */

const STUDIES = (existsSync(at('content/studies')) ? readdirSync(at('content/studies')) : [])
  .filter((f) => f.endsWith('.html'))
  .map((f) => {
    const slug = f.replace(/\.html$/, '');
    const text = read(`content/studies/${f}`);
    const head = text.match(/^<!--([\s\S]*?)-->/);
    const meta = Object.fromEntries((head ? head[1] : '').split('\n').map((l) => l.match(/^\s*(\w+):\s*(.+?)\s*$/)).filter(Boolean).map((m) => [m[1], m[2]]));
    if (!/^[a-z0-9-]+$/.test(slug)) fail(`content/studies/${f}: use lowercase letters, numbers and hyphens in the file name.`);
    for (const key of ['title', 'summary', 'order']) if (!meta[key]) fail(`content/studies/${f}: no ${key}.`);
    return { slug, ...meta, order: Number(meta.order), body: text.slice(head[0].length).trim() };
  })
  .sort((a, b) => a.order - b.order);
const STUDIES_ON_HOME = 3;   // how many the home page shows (the first, in order)

/* ---------- The drop-down menus, About us and the page heads ----------
   Written into index.html between its markers, then copied with the header
   onto every page:
     <!-- menu:treatments --> every standard drip (not the Pro versions), with its mini drawing (the line
       drawings as one icon file, images/icons/treatments.svg), name and price;
     <!-- menu:studies --> every study;
     <!-- studies:home --> the first studies, as cards;
     <!-- head:meta --> the robots, link-preview and search details;
     data-gmc / data-cqc: the doctors' GMC numbers and the CQC line. */

const ICON_FILE = 'images/icons/treatments.svg';
const iconHTML = (art) => (art ? `<svg class="menu-icon" viewBox="0 0 400 400" aria-hidden="true" focusable="false"><use href="${ICON_FILE}#art-${esc(art)}"/></svg>` : '<span class="menu-icon menu-icon--none" aria-hidden="true"></span>');
// Every standard drip, like the cards: a Pro version is reached from its
// standard version's page and card ("Upgrade to Pro").
function treatmentsMenuHTML() {
  return `<ul class="menu-list menu-list--icons">${DRIPS.filter((d) => !d.baseVariantSlug).map((d) => {
    const art = USE_LINES ? VISUALS[d.slug].art : null;
    return `
              <li><a class="menu-item" href="treatments/${esc(d.slug)}/">${iconHTML(art)}<span class="menu-item__text"><span class="menu-item__name"><span${vb(`drips.${d.slug}.name`)}>${esc(d.name)}</span></span><span class="menu-item__price"${vb(`drips.${d.slug}.priceLabel`)}>${esc(d.priceLabel)}</span></span></a></li>`;
  }).join('')}
            </ul>`;
}
function studiesMenuHTML() {
  return `<ul class="menu-list">${STUDIES.map((st) => `
              <li><a class="menu-item menu-item--text" href="studies/${esc(st.slug)}/">${esc(st.title)}</a></li>`).join('')}
            </ul>`;
}
const studyCardHTML = (st, up, h) => `
          <li class="study-card">
            <h${h} class="study-card__title"><a class="study-card__link" href="${up}studies/${esc(st.slug)}/">${esc(st.title)}</a></h${h}>
            <p class="study-card__summary">${esc(st.summary)}</p>
            <p class="study-card__more" aria-hidden="true">Read the summary</p>
          </li>`;
// h: the cards' heading level (3 under a section's h2; 2 on the studies page).
const studyCardsHTML = (list, up, h = 3) => `<ul class="study-grid">${list.map((st) => studyCardHTML(st, up, h)).join('')}
        </ul>`;

// The robots line (until launch), the link preview and, on the home page, the
// clinic's details for search engines.
function headMeta({ title, description, path = '', home = false }) {
  const lines = [];
  if (!isOn('launched')) lines.push('<meta name="robots" content="noindex, nofollow">');
  else if (SITE_URL) lines.push(`<link rel="canonical" href="${esc(SITE_URL + path)}">`);
  lines.push('<meta property="og:type" content="website">');
  lines.push(`<meta property="og:site_name" content="${esc(SITE_NAME)}">`);
  lines.push(`<meta property="og:title" content="${esc(title)}">`);
  if (description) lines.push(`<meta property="og:description" content="${esc(description)}">`);
  if (SITE_URL) {
    lines.push(`<meta property="og:url" content="${esc(SITE_URL + path)}">`);
    lines.push(`<meta property="og:image" content="${esc(SITE_URL)}images/share.png">`);
    lines.push('<meta property="og:image:width" content="1200">', '<meta property="og:image:height" content="630">');
    lines.push(`<meta property="og:image:alt" content="${esc(`${SITE_NAME}: doctor-led IV drips, London`)}">`);
  }
  lines.push('<meta name="twitter:card" content="summary_large_image">');
  if (home) {
    const clinic = {
      '@context': 'https://schema.org',
      '@type': 'MedicalClinic',
      name: SITE_NAME,
      description: 'Doctor-led IV drips in clinic near Westfield, London, and as a mobile call-out.',
      address: { '@type': 'PostalAddress', streetAddress: SITE.clinicAddress || 'Bluebird Dentists, near Westfield', addressLocality: 'London', addressCountry: 'GB' },
    };
    if (SITE_URL) { clinic.url = SITE_URL; clinic.image = `${SITE_URL}images/share.png`; }
    if (SITE.phone) clinic.telephone = SITE.phone;
    if (SITE.email) clinic.email = SITE.email;
    lines.push(`<script type="application/ld+json">${JSON.stringify(clinic).replace(/</g, '\\u003c')}</script>`);
  }
  return lines.join('\n  ');
}

// The doctors' GMC numbers and the CQC line in About us.
function gmcHTML(key) {
  const n = SITE[key];
  return n ? `GMC number: <a href="https://www.gmc-uk.org/registrants/${esc(n)}">${esc(n)}</a>` : 'GMC number: <mark class="legal-gap">[GMC number]</mark>';
}
function cqcHTML() {
  if (SITE.cqcRating) {
    const date = SITE.cqcRatingDate ? ` (report published ${esc(SITE.cqcRatingDate)})` : '';
    const link = SITE.cqcReportUrl ? ` <a href="${esc(SITE.cqcReportUrl)}">Read the report on the CQC website</a>.` : '';
    return `Rated <strong>${esc(SITE.cqcRating)}</strong> by the Care Quality Commission${date}.${link}`;
  }
  if (SITE.cqcNumber) return `Registered with the Care Quality Commission (ID ${esc(SITE.cqcNumber)}).`;
  return 'Care Quality Commission: <mark class="legal-gap">[registration, and the clinic\'s latest rating once inspected]</mark>';
}

const region = (html, name, content) => {
  const re = new RegExp(`(<!-- ${name} -->)[\\s\\S]*?(<!-- /${name} -->)`, 'g');
  if (!re.test(html)) fail(`index.html has no <!-- ${name} --> … <!-- /${name} --> markers.`);
  return html.replace(re, (m, open, close) => `${open}\n            ${content}\n            ${close}`);
};
const withContent = (html) => {
  let out = region(html, 'menu:treatments', treatmentsMenuHTML());
  out = region(out, 'menu:studies', studiesMenuHTML());
  out = region(out, 'studies:home', studyCardsHTML(STUDIES.slice(0, STUDIES_ON_HOME), ''));
  out = out.replace(/(<!-- head:meta [\s\S]*?-->)[\s\S]*?(<!-- \/head:meta -->)/, (m, open, close) => `${open}\n  ${headMeta({
    title: 'Bluebird Wellness | Doctor-led IV drips in clinic and at home, London',
    description: 'Doctor-led IV drips at Bluebird Dentists near Westfield, London, or as a mobile call-out to your home, hotel or office.',
    home: true,
  })}\n  ${close}`);
  out = out.replace(/(<p class="doctor__gmc" data-gmc="(\w+)">)[\s\S]*?(<\/p>)/g, (m, open, key, close) => `${open}${gmcHTML(key)}${close}`);
  out = out.replace(/(<p class="about__regulator" data-cqc>)[\s\S]*?(<\/p>)/, (m, open, close) => `${open}${cqcHTML()}${close}`);
  return out;
};

/* ---------- Header and footer: the home page's, pointed back at it ---------- */

const INDEX = withLogo(withSite(withContent(read('index.html'))));

function slice(html, open, close) {
  const start = html.indexOf(open);
  const end = html.indexOf(close, start);
  if (start < 0 || end < 0) fail(`Could not find ${open} … ${close} in index.html.`);
  return html.slice(start, end + close.length);
}

// In-page links go back to the home page and relative links are re-pointed
// from the page's folder (up: "../../" from a treatment page, "../" from the
// glossary).
const rebase = (html, up) =>
  html
    .replace(/href="(?!#|\/|[a-z][a-z0-9+.-]*:)([^"]+)"/gi, `href="${up}$1"`)
    .replace(/href="#top"/g, `href="${up}"`)
    .replace(/href="#([A-Za-z][^"]*)"/g, `href="${up}#$1"`);

// The header runs to the end of the phones' menu, which follows it.
const HEADER_HTML = slice(INDEX, '<header class="site-header"', '<!-- end of the site menu -->');
const FOOTER_HTML = slice(INDEX, '<footer class="site-footer">', '</footer>');
const HEADER = rebase(HEADER_HTML, '../../');
const FOOTER = rebase(FOOTER_HTML, '../../');
// On the glossary itself, its own links point at the page and are marked current.
const GLOSSARY_HEADER = rebase(HEADER_HTML, '../').replace(/<a href="\.\.\/ingredients\/">/g, '<a href="./" aria-current="page">');
const GLOSSARY_FOOTER = rebase(FOOTER_HTML, '../').replace(/href="\.\.\/ingredients\/"/g, 'href="./"');
// The favicons, as the home page has them.
const ICONS = [...INDEX.matchAll(/<link rel="(?:icon|apple-touch-icon)"[^>]*>/g)].map((m) => m[0]).join('\n  ');
if (!ICONS) fail('No favicon links in index.html.');
// A Book button on another page, as the header's are.
const bookHref = (up) => (SITE.bookingUrl ? esc(SITE.bookingUrl) : `${up}#book`);

/* ---------- Treatment page ---------- */

// A treatment's line drawing (a Pro drip shows its standard version's), as
// inline SVG; site.js draws it in from the top down as it comes into view.
function lineArtSVG(art, idPrefix) {
  const clips = [];
  const paths = art.paths.map((p, k) => {
    const o = typeof p === 'string' ? { d: p } : p;
    const move = o.transform ? ` transform="${esc(o.transform)}"` : '';
    if (!o.fill) return `<path d="${esc(o.d)}"${move}/>`;
    const [x, y, w, h] = o.box;
    clips.push(`<clipPath id="${idPrefix}-${k}"><rect x="${x}" y="${y}" width="${w}" height="${h}" data-h="${h}"/></clipPath>`);
    return `<path class="tx-art__fill" d="${esc(o.d)}"${move} clip-path="url(#${idPrefix}-${k})"/>`;
  }).join('');
  return `<svg class="line-art" viewBox="0 0 400 400" data-draw aria-hidden="true" focusable="false"><defs>${clips.join('')}</defs><g class="tx-art">${paths}</g></svg>`;
}

function pictureHTML(drip, v) {
  const art = USE_LINES && v.art && LINE_ART[v.art];
  if (art) {
    return `<div class="drip-picture drip-picture--art" role="img" aria-label="${esc(art.alt)}">
            ${lineArtSVG(art, 'art-clip')}
          </div>`;
  }
  if (!v.image) {
    return `<div class="drip-picture drip-picture--placeholder" data-reveal-load>
            <!-- No picture yet. Save it as images/treatments/${drip.slug}.webp and run the generator.
                 imageBrief: ${commentText(drip.imageBrief || '')} -->
            <span class="placeholder placeholder--${esc(v.placeholder.shape)}" style="--ph: ${esc(v.placeholder.colour)}" aria-hidden="true"></span>
          </div>`;
  }
  const [w, h] = v.imageSize;
  const cls = v.imageFit === 'cover' ? 'drip-picture drip-picture--photo' : 'drip-picture';
  return `<div class="${cls}" data-reveal-load>
            <img src="../../${esc(v.image)}" alt="${esc(v.alt)}" width="${w}" height="${h}" fetchpriority="high" decoding="async">
          </div>`;
}

const ARROW = '<svg class="variant-link__icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h10M9 4l4 4-4 4"/></svg>';
const BACK = '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M13 8H3M7 4 3 8l4 4"/></svg>';

// "PRO" beside a Pro drip's name (the name already says Pro, so screen readers skip it).
const PRO_BADGE = '<span class="pro-badge" aria-hidden="true">Pro</span>';

// On a standard drip with a Pro version: the "Upgrade to Pro" card, with the
// Pro drip's name, price, what it adds and a link to its page.
function upgradeHTML(drip) {
  const pro = bySlug[drip.proVariantSlug];
  if (!pro) return '';
  const q = `drips.${pro.slug}`;
  const { adds } = proAdds(drip, pro);
  const list = adds.length ? `
            <p class="upgrade__adds-title" id="upgrade-adds">Pro adds</p>
            <ul class="upgrade__adds" aria-labelledby="upgrade-adds">
${adds.map((a) => `              <li${vb(`${q}.ingredients.${a.i}`)}>${esc(a.line)}</li>`).join('\n')}
            </ul>` : '';
  return `
          <aside class="upgrade" aria-labelledby="upgrade-title">
            <p class="eyebrow">Upgrade to Pro</p>
            <h2 class="upgrade__title" id="upgrade-title"><span${vb(`${q}.name`)}>${esc(pro.name)}</span> ${PRO_BADGE}</h2>
            <p class="upgrade__price"${vb(`${q}.priceLabel`)}>${esc(pro.priceLabel)}</p>${list}
            <a class="btn btn--secondary btn--compact" href="../${esc(pro.slug)}/">Learn more<span class="visually-hidden"> about ${esc(pro.name)}</span></a>
          </aside>`;
}

// On a Pro drip: the quiet link back to its standard version.
function variantHTML(drip) {
  const other = bySlug[drip.baseVariantSlug];
  if (!other) return '';
  return `
          <p class="drip-variant">
            <a class="variant-link" href="../${esc(other.slug)}/"><span${vb(`drips.${other.slug}.name`)}>${esc(other.name)}</span> <span class="variant-link__price"${vb(`drips.${other.slug}.priceLabel`)}>${esc(other.priceLabel)}</span>${ARROW}</a>
          </p>`;
}

function priceTableHTML(table, path, caption) {
  const head = table.columns.map((c, i) => `<th scope="col"${vb(`${path}.columns.${i}`)}>${esc(c)}</th>`).join('');
  const rows = table.rows.map((row, r) => {
    const cells = row.map((cell, c) => (c === 0
      ? `<th scope="row"${vb(`${path}.rows.${r}.${c}`)}>${esc(cell)}</th>`
      : `<td${vb(`${path}.rows.${r}.${c}`)}>${esc(cell)}</td>`)).join('');
    return `              <tr>${cells}</tr>`;
  }).join('\n');
  return `<table class="price-table">
              ${caption}
              <thead><tr>${head}</tr></thead>
              <tbody>
${rows}
              </tbody>
            </table>`;
}

// A description's name in bold, linking to its glossary entry when it has one.
function descriptionNameHTML(d, path, up) {
  const entry = glossaryFor(d.name);
  const name = `<span${vb(`${path}.name`)}>${esc(d.name)}</span>`;
  return entry
    ? `<p class="ingredient__name"><a class="ingredient__link" href="${up}ingredients/#${esc(entry.id)}">${name}</a></p>`
    : `<p class="ingredient__name">${name}</p>`;
}

// An accordion row: the summary, then the description's name and text.
function ingredientDetailsHTML(summary, d, path, indent) {
  return `${indent}<details class="accordion__item ingredient">
${indent}  <summary class="accordion__summary">${summary}</summary>
${indent}  <div class="accordion__body">
${indent}    ${descriptionNameHTML(d, path, '../../')}
${indent}    <div class="ingredient__text"${vb(`${path}.text`)}>
${paras(d.text, `${indent}      `)}
${indent}    </div>
${indent}  </div>
${indent}</details>`;
}

// One list of the drip's ingredients, exactly as written, in the menu's
// order. A line with a description opens to show it; the base solution's
// lines are grouped under it; notes are small print below the list.
function ingredientsHTML(drip, p) {
  if (!drip.ingredients.length && !drip.ingredientDescriptions.length) return '';
  const { rows, notes, unmatched } = ingredientRows(drip);
  const I = '              ';
  const line = (row) => `<span${vb(`${p}.ingredients.${row.i}`)}>${esc(row.line)}</span>`;
  const rowHTML = (row) => {
    const group = row.children.length ? `
${I}  <ul class="ingredients__group">
${row.children.map((child) => `${I}    <li>${line(child)}</li>`).join('\n')}
${I}  </ul>` : '';
    if (!row.desc) return `${I}<li class="ingredients__plain">${line(row)}${group}</li>`;
    return `${I}<li>
${ingredientDetailsHTML(line(row), row.desc, `${p}.ingredientDescriptions.${row.desc.j}`, `${I}  `)}${group}
${I}</li>`;
  };
  const extra = unmatched.map((d) => `${I}<li>
${ingredientDetailsHTML(`<span${vb(`${p}.ingredientDescriptions.${d.j}.name`)}>${esc(d.name)}</span>`, d, `${p}.ingredientDescriptions.${d.j}`, `${I}  `)}
${I}</li>`);
  const hasDetails = rows.some((r) => r.desc) || unmatched.length;
  const toggle = hasDetails
    ? `
            <button type="button" class="btn btn--secondary btn--compact" data-expand-all aria-controls="ingredient-list" hidden>Expand all</button>` : '';
  const small = notes.map((n) => `
          <p class="ingredients__note"${vb(`${p}.ingredients.${n.i}`)}>${esc(n.line)}</p>`).join('');
  return `
    <section class="drip-section" id="ingredients" aria-labelledby="ingredients-title">
      <div class="container">
        <div class="ingredients" data-fade>
          <div class="ingredients__head">
            <h2 class="drip-section__title" id="ingredients-title">Ingredients</h2>${toggle}
          </div>
          <ul class="ingredients__list" id="ingredient-list">
${[...rows.map(rowHTML), ...extra].join('\n')}
          </ul>${small}
          <p class="ingredients__glossary"><a class="link" href="../../ingredients/">Ingredient glossary</a></p>
        </div>
      </div>
    </section>`;
}

function pricesHTML(drip, p) {
  if (!drip.priceTable && !drip.pricingNote) return '';
  const note = drip.pricingNote ? `
        <div class="drip-prose" data-fade${vb(`${p}.pricingNote`)}>
${paras(drip.pricingNote, '          ')}
        </div>` : '';
  const caption = drip.priceTableLabel ? `<caption${vb(`${p}.priceTableLabel`)}>${esc(drip.priceTableLabel)}</caption>` : '';
  const table = drip.priceTable ? `
        <div class="price-table-wrap" data-fade>
          ${priceTableHTML(drip.priceTable, `${p}.priceTable`, caption)}
        </div>` : '';
  return `
    <section class="drip-section" aria-labelledby="prices">
      <div class="container">
        <h2 class="drip-section__title" id="prices" data-fade>Prices</h2>${note}${table}
      </div>
    </section>`;
}

// Iron's long read: the intro, a contents list and its sections.
function longFormHTML(drip, p) {
  if (!drip.sections?.length && !drip.moreInfoIntro) return '';
  const ids = (drip.sections || []).map((s) => slugify(s.heading));
  const intro = drip.moreInfoIntro ? `
        <div class="drip-prose drip-prose--lead" data-fade${vb(`${p}.moreInfoIntro`)}>
${paras(drip.moreInfoIntro, '          ')}
        </div>` : '';
  const toc = drip.sections?.length ? `
        <nav class="toc" id="contents" aria-labelledby="contents-title" data-fade>
          <h2 class="toc__title" id="contents-title">Contents</h2>
          <ol class="toc__list">
${drip.sections.map((s, i) => `            <li><a class="link" href="#${ids[i]}"${vb(`${p}.sections.${i}.heading`)}>${esc(s.heading)}</a></li>`).join('\n')}
          </ol>
        </nav>` : '';
  const sections = (drip.sections || []).map((s, i) => `
        <section class="longform-section" id="${ids[i]}" aria-labelledby="${ids[i]}-title">
          <h2 class="drip-section__title" id="${ids[i]}-title" data-fade${vb(`${p}.sections.${i}.heading`)}>${esc(s.heading)}</h2>
          <div class="drip-prose" data-fade${vb(`${p}.sections.${i}.body`)}>
${paras(s.body, '            ')}
          </div>
        </section>`).join('');
  return `
    <div class="drip-longform">
      <div class="container">${intro}${toc}${sections}
      </div>
    </div>`;
}

function footnotesHTML(drip, p) {
  if (!drip.footnotes?.length) return '';
  const items = drip.footnotes.map((f, i) => {
    const n = (String(f).match(/^\d+/) || [String(i + 1)])[0];
    return `          <li id="footnote-${n}"${vb(`${p}.footnotes.${i}`)}>${esc(f)}</li>`;
  }).join('\n');
  return `
    <section class="drip-section drip-footnotes" aria-label="Footnotes">
      <div class="container">
        <ol class="footnotes">
${items}
        </ol>
      </div>
    </section>`;
}

// Phones: links to the page's own sections, under the price, in page order.
function jumpsHTML(drip) {
  const links = [];
  if (drip.sections?.length) links.push(['#contents', 'Contents']);
  if (drip.ingredients.length || drip.ingredientDescriptions.length) links.push(['#ingredients', 'Ingredients']);
  if (drip.priceTable || drip.pricingNote) links.push(['#prices', 'Prices']);
  if (!links.length) return '';
  return `
          <nav class="drip-jumps" aria-label="On this page">
            <ul>${links.map(([href, label]) => `<li><a href="${href}">${label}</a></li>`).join('')}</ul>
          </nav>`;
}

function pageHTML(drip) {
  const p = `drips.${drip.slug}`;
  const v = VISUALS[drip.slug];
  // With the line drawings, every treatment page is on the palest violet (the
  // page's own colour); with the photos, on the tint its pictures were made on.
  const tint = (!USE_LINES && v.tint) || '#F6F3FE';
  const tagline = drip.tagline ? `
          <p class="drip-tagline"${vb(`${p}.tagline`)}>${esc(drip.tagline)}</p>` : '';
  const badge = v.badge ? `<span class="${v.badge.variant === 'sage' ? 'badge badge--sage' : 'badge'}">${esc(v.badge.text)}</span>` : '';

  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="en-GB" style="--page-tint: ${esc(tint)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(drip.name)} | ${esc(SITE_NAME)}</title>
  <meta name="theme-color" content="${esc(tint)}">
  ${headMeta({ title: `${drip.name} | ${SITE_NAME}`, description: `${drip.name}, ${drip.priceLabel}: a doctor-led IV drip at ${SITE_NAME}, London. Every treatment is subject to a medical consultation.`, path: `treatments/${drip.slug}/` })}
  ${rebase(ICONS, '../../')}

  <link rel="preload" href="../../fonts/Inter-Regular.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="../../styles.css">
</head>
<body class="drip-page" data-book-item="${esc(drip.name)}">
  <a class="skip-link" href="#main">Skip to content</a>

  ${HEADER}

  <main id="main">
    <div class="drip-intro">
      <div class="container drip-intro__inner">
        <div class="drip-intro__text">
          <a class="drip-back" href="../../#treatments">${BACK}Back to all treatments</a>
          <h1 class="drip-title"><span${vb(`${p}.name`)}>${esc(drip.name)}</span>${drip.baseVariantSlug ? ` ${PRO_BADGE}` : ''}</h1>${tagline}
          <div class="drip-meta" data-main-price>
            <p class="drip-price"${vb(`${p}.priceLabel`)}>${esc(drip.priceLabel)}</p>
            ${badge}
          </div>${jumpsHTML(drip)}${variantHTML(drip)}${upgradeHTML(drip)}
          <div class="drip-prose drip-description"${vb(`${p}.description`)}>
${paras(drip.description, '            ')}
          </div>
        </div>
        <div class="drip-intro__media">
          ${pictureHTML(drip, v)}
        </div>
      </div>
    </div>
${longFormHTML(drip, p)}${ingredientsHTML(drip, p)}${pricesHTML(drip, p)}${footnotesHTML(drip, p)}

    <section class="drip-book" aria-label="Book" data-book-section>
      <div class="container">
        <div class="drip-book__panel" data-fade>
          <a class="btn btn--primary" href="${bookHref('../../')}" data-book>Book now<span class="visually-hidden"> ${esc(drip.name)}</span></a>
          <p class="drip-disclaimer"${vb('disclaimer')}>${esc(MENU.disclaimer)}</p>
          <a class="drip-back" href="../../#treatments">${BACK}Back to all treatments</a>
        </div>
      </div>
    </section>
  </main>

  <!-- Phones: the price and Book, once the main price has scrolled away -->
  <div class="book-bar" data-book-bar aria-hidden="true">
    <div class="container book-bar__inner">
      <p class="book-bar__price"${vb(`${p}.priceLabel`)}>${esc(drip.priceLabel)}</p>
      <a class="btn btn--primary" href="${bookHref('../../')}" data-book tabindex="-1">Book<span class="visually-hidden"> ${esc(drip.name)}</span></a>
    </div>
  </div>

  ${FOOTER}

  <script src="../../site-config.js" defer></script>
  <script src="../../data/book-list.js" defer></script>
  <script src="../../site.js" defer></script>
  <script src="../../treatment.js" defer></script>
  <script src="../../booking.js" defer></script>
  <script src="../../chat.js" defer></script>
</body>
</html>
`;
}

/* ---------- Ingredient glossary (ingredients/) ---------- */

const GLOSSARY_TITLE = 'Ingredient glossary';

// Where a glossary entry is used: every drip with a line of that name, and
// the standalone section when it is one of the standalone boosters.
function usedIn(item) {
  const drips = DRIPS.filter((d) => d.ingredients.some((line) => !isNote(line) && nameKey(line) === item.key));
  const standalone = (MENU.standalone?.ingredientDescriptions || []).some((d) => nameKey(d.name) === item.key);
  return { drips, standalone };
}

function glossaryPageHTML() {
  const cats = GLOSSARY.map((c) => `
            <li><a class="glossary-cats__link" href="#${esc(c.id)}"${vb(`${c.path}.category`)}>${esc(c.category)}</a></li>`).join('');
  const sections = GLOSSARY.map((c) => {
    const items = c.items.map((item) => {
      const { drips, standalone } = usedIn(item);
      const links = [
        ...drips.map((d) => `<li><a class="used-in__link" href="../treatments/${esc(d.slug)}/"${vb(`drips.${d.slug}.name`)}>${esc(d.name)}</a></li>`),
        ...(standalone ? [`<li><a class="used-in__link" href="../#standalone"${vb('standalone.heading')}>${esc(MENU.standalone.heading)}</a></li>`] : []),
      ];
      const used = links.length ? `
              <div class="used-in">
                <p class="used-in__label" id="${esc(item.id)}-used">Used in</p>
                <ul class="used-in__list" aria-labelledby="${esc(item.id)}-used">
                  ${links.join('\n                  ')}
                </ul>
              </div>` : '';
      return `
            <details class="accordion__item" id="${esc(item.id)}" data-glossary-item data-name="${esc(item.name)}">
              <summary class="accordion__summary"><span${vb(`${item.path}.name`)}>${esc(item.name)}</span></summary>
              <div class="accordion__body">
                <div class="glossary-text"${vb(`${item.path}.text`)}>
${paras(item.text, '                  ')}
                </div>${used}
              </div>
            </details>`;
    }).join('');
    return `
        <section class="glossary-section" id="${esc(c.id)}" aria-labelledby="${esc(c.id)}-title" data-glossary-category>
          <h2 class="glossary-section__title" id="${esc(c.id)}-title"${vb(`${c.path}.category`)}>${esc(c.category)}</h2>
          <div class="accordion">${items}
          </div>
        </section>`;
  }).join('');

  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(GLOSSARY_TITLE)} | ${esc(SITE_NAME)}</title>
  <meta name="theme-color" content="#F6F3FE">
  ${headMeta({ title: `${GLOSSARY_TITLE} | ${SITE_NAME}`, description: `What's in ${SITE_NAME}'s IV drips: every ingredient, and the drips it's in.`, path: 'ingredients/' })}
  ${rebase(ICONS, '../')}

  <link rel="preload" href="../fonts/Inter-Regular.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="../styles.css">
</head>
<body class="drip-page glossary-page">
  <a class="skip-link" href="#main">Skip to content</a>

  ${GLOSSARY_HEADER}

  <main id="main">
    <div class="glossary-intro">
      <div class="container glossary">
        <a class="drip-back" href="../#treatments">${BACK}Back to all treatments</a>
        <h1 class="drip-title">${esc(GLOSSARY_TITLE)}</h1>
      </div>
    </div>
    <!-- On phones the search and the categories stay under the header -->
    <div class="glossary-bar" data-glossary-bar>
      <div class="container glossary">
        <div class="glossary-search" data-glossary-search hidden>
          <label class="glossary-search__label" for="glossary-search">Search ingredients</label>
          <input class="glossary-search__input" type="search" id="glossary-search" placeholder="Search ingredients" autocomplete="off" spellcheck="false" aria-controls="glossary-entries">
        </div>
        <nav class="glossary-cats" aria-label="Categories">
          <ul class="glossary-cats__list">${cats}
          </ul>
        </nav>
      </div>
    </div>
    <div class="glossary-tools-row">
      <div class="container glossary glossary-tools">
        <button type="button" class="btn btn--secondary btn--compact" data-expand-all aria-controls="glossary-entries" hidden>Expand all</button>
      </div>
    </div>

    <div class="container glossary glossary-entries" id="glossary-entries">${sections}
      <p class="glossary-empty" data-glossary-empty role="status" hidden>No ingredients match that search.</p>
    </div>

    <section class="drip-book" aria-label="Book">
      <div class="container glossary">
        <div class="drip-book__panel" data-fade>
          <a class="btn btn--primary" href="${bookHref('../')}" data-book>Book now</a>
          <p class="drip-disclaimer"${vb('disclaimer')}>${esc(MENU.disclaimer)}</p>
          <a class="drip-back" href="../#treatments">${BACK}Back to all treatments</a>
        </div>
      </div>
    </section>
  </main>

  <a class="to-top" href="#main" data-to-top>
    <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 13V3M4 7l4-4 4 4"/></svg>
    <span>Back to top</span>
  </a>

  ${GLOSSARY_FOOTER}

  <script src="../site-config.js" defer></script>
  <script src="../data/book-list.js" defer></script>
  <script src="../site.js" defer></script>
  <script src="../treatment.js" defer></script>
  <script src="../booking.js" defer></script>
  <script src="../chat.js" defer></script>
</body>
</html>
`;
}

/* ---------- Policy pages ----------
   privacy/, terms/, cancellations/, cookies/ and accessibility/, written from
   content/legal/<name>.html (a comment with the title and description, then
   the page's text). In the text, {{name}} is a value from site-config.js
   (a highlighted gap until it's filled in), {{businessDetails}} is the list
   of the business's details, and [[text]] is a highlighted gap for something
   the clinic still has to decide. */

const LEGAL = ['privacy', 'terms', 'cancellations', 'cookies', 'accessibility', 'complaints', 'faq'];
const LEGAL_GAPS = {
  legalName: "the business's legal name",
  companyNumber: 'company number, if a limited company',
  registeredIn: 'where the company is registered',
  registeredOffice: 'registered office address',
  clinicAddress: "the clinic's full address",
  vatNumber: 'VAT number, if VAT-registered',
  icoNumber: 'ICO registration number',
  cqcNumber: 'Care Quality Commission ID, if registered',
  bookingProvider: "the booking system's provider",
  callOutFee: 'the call-out charge, or "none"',
  cancellationNotice: 'how much notice, e.g. 24 hours',
  cancellationFee: 'the charge, e.g. 50% of the treatment price',
  minimumAge: 'the minimum age',
  policiesUpdated: 'the date',
  email: "the clinic's email address",
  phone: "the clinic's phone number",
};
const LEGAL_DEFAULTS = { clinicAddress: 'Bluebird Dentists, near Westfield, London' };
const legalGap = (text) => `<mark class="legal-gap">[${esc(text)}]</mark>`;
const legalValue = (key) => SITE[key] || LEGAL_DEFAULTS[key] || '';
function legalField(key) {
  if (key === 'businessDetails') return businessDetailsHTML();
  if (!(key in LEGAL_GAPS)) fail(`content/legal: unknown {{${key}}}.`);
  const value = legalValue(key);
  if (!value) return legalGap(LEGAL_GAPS[key]);
  if (key === 'email') return `<a href="mailto:${esc(value)}">${esc(value)}</a>`;
  if (key === 'phone') return `<a href="${esc(contactHref.phone(value))}">${esc(value)}</a>`;
  return esc(value);
}
function businessDetailsHTML() {
  const rows = [
    ['Business', 'legalName'],
    ['Company number', 'companyNumber'],
    ['Registered in', 'registeredIn'],
    ['Registered office', 'registeredOffice'],
    ['Clinic', 'clinicAddress'],
    ['VAT number', 'vatNumber'],
    ['ICO registration', 'icoNumber'],
    ['Care Quality Commission', 'cqcNumber'],
    ['Phone', 'phone'],
    ['Email', 'email'],
  ];
  return `<dl class="legal-details">${rows.map(([label, key]) => `
  <div><dt>${esc(label)}</dt><dd>${legalField(key)}</dd></div>`).join('')}
</dl>`;
}
function legalSource(name) {
  const text = read(`content/legal/${name}.html`);
  const head = text.match(/^<!--([\s\S]*?)-->/);
  const meta = Object.fromEntries((head ? head[1] : '').split('\n').map((l) => l.match(/^\s*(\w+):\s*(.+?)\s*$/)).filter(Boolean).map((m) => [m[1], m[2]]));
  if (!meta.title) fail(`content/legal/${name}.html: no title.`);
  const body = text.slice(head ? head[0].length : 0).trim()
    .replace(/\{\{(\w+)\}\}/g, (m, key) => legalField(key))
    .replace(/\[\[([^\]]+)\]\]/g, (m, gapText) => legalGap(gapText));
  return { name, title: meta.title, description: meta.description || '', body };
}
function legalPageHTML(name) {
  const page = legalSource(name);
  const header = rebase(HEADER_HTML, '../');
  const footer = rebase(FOOTER_HTML, '../').replace(`<a href="../${name}/">`, '<a href="./" aria-current="page">');
  const sections = [...page.body.matchAll(/<h2 id="([^"]+)">([\s\S]*?)<\/h2>/g)];
  const toc = sections.length > 2 ? `
      <nav class="legal-toc" aria-labelledby="legal-toc-title">
        <p class="legal-toc__title" id="legal-toc-title">On this page</p>
        <ul>${sections.map((m) => `
          <li><a href="#${m[1]}">${m[2]}</a></li>`).join('')}
        </ul>
      </nav>` : '';
  const draft = SITE.legalDraft !== 'false' ? `
      <p class="legal-draft" role="note"><strong>Draft.</strong> This page is waiting for the clinic's details (highlighted) and a compliance review.</p>` : '';
  return `<!DOCTYPE html>
<!-- ${GENERATED} (from content/legal/${name}.html) -->
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(page.title)} | ${esc(SITE_NAME)}</title>
  <meta name="description" content="${esc(page.description)}">
  <meta name="theme-color" content="#F6F3FE">
  ${headMeta({ title: `${page.title} | ${SITE_NAME}`, description: page.description, path: `${name}/` })}
  ${rebase(ICONS, '../')}

  <link rel="preload" href="../fonts/Inter-Regular.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="../styles.css">
</head>
<body class="drip-page legal-page">
  <a class="skip-link" href="#main">Skip to content</a>

  ${header}

  <main id="main">
    <article class="container legal">
      <h1 class="drip-title">${esc(page.title)}</h1>
      <p class="legal-updated">Last updated ${legalField('policiesUpdated')}</p>${draft}
      <div class="legal-body">
${page.body.replace(/^(<p class="legal-lead">[\s\S]*?<\/p>)/, `$1${toc}`)}
      </div>
    </article>
  </main>

  ${footer}

  <script src="../site-config.js" defer></script>
  <script src="../data/book-list.js" defer></script>
  <script src="../site.js" defer></script>
  <script src="../treatment.js" defer></script>
  <script src="../booking.js" defer></script>
  <script src="../chat.js" defer></script>
</body>
</html>
`;
}

/* ---------- Studies pages ---------- */

const STUDIES_TITLE = 'Studies';
const STUDIES_LEAD = 'Plain-English summaries of what UK surveys, NHS and NICE guidance and published research say about common deficiencies, with every source listed.';
// Shown on every study: they're general information, and they say nothing about our treatments.
const STUDY_NOTICE = `<div class="study-notice" role="note">
        <p><strong>General information, not medical advice.</strong> These summaries describe what published research and UK guidance say. They are not about our treatments, and they can't tell you whether you have a deficiency: only a doctor and, often, a blood test can.</p>
        <p>If you're worried about symptoms, speak to your GP or a pharmacist, or call NHS 111. In an emergency, call 999.</p>
      </div>`;
const studyDraft = () => (isOn('studiesReviewed') ? '' : `
      <p class="legal-draft" role="note"><strong>Draft.</strong> This summary is awaiting review by the clinic's doctors.</p>`);

function pageShell({ up, title, description, path, bodyClass, main, current }) {
  let header = rebase(HEADER_HTML, up);
  let footer = rebase(FOOTER_HTML, up);
  if (current) {
    header = header.replace(new RegExp(`<a href="${up}${current}">`, 'g'), '<a href="./" aria-current="page">');
    footer = footer.replace(new RegExp(`<a href="${up}${current}">`, 'g'), '<a href="./" aria-current="page">');
  }
  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(title)} | ${esc(SITE_NAME)}</title>
  <meta name="description" content="${esc(description)}">
  <meta name="theme-color" content="#4A2696">
  ${headMeta({ title: `${title} | ${SITE_NAME}`, description, path })}
  ${rebase(ICONS, up)}

  <link rel="preload" href="${up}fonts/Inter-Regular.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="${up}styles.css">
</head>
<body class="drip-page ${bodyClass}">
  <a class="skip-link" href="#main">Skip to content</a>

  ${header}

  <main id="main">
${main}
  </main>

  ${footer}

  <script src="${up}site-config.js" defer></script>
  <script src="${up}data/book-list.js" defer></script>
  <script src="${up}site.js" defer></script>
  <script src="${up}treatment.js" defer></script>
  <script src="${up}booking.js" defer></script>
  <script src="${up}chat.js" defer></script>
</body>
</html>
`;
}

function studiesIndexHTML() {
  return pageShell({
    up: '../', title: STUDIES_TITLE, description: STUDIES_LEAD, path: 'studies/', bodyClass: 'studies-page', current: 'studies/',
    main: `    <div class="container legal studies-index">
      <p class="drip-back-row"><a class="drip-back" href="../#studies">${BACK}Back to the home page</a></p>
      <h1 class="drip-title">${esc(STUDIES_TITLE)}</h1>
      <p class="legal-lead">${esc(STUDIES_LEAD)}</p>
      ${STUDY_NOTICE}
      ${studyCardsHTML(STUDIES, '../', 2)}
    </div>`,
  });
}

function studyPageHTML(st) {
  const sections = [...st.body.matchAll(/<h2 id="([^"]+)">([\s\S]*?)<\/h2>/g)];
  const toc = sections.length > 2 ? `
      <nav class="legal-toc" aria-labelledby="study-toc-title">
        <p class="legal-toc__title" id="study-toc-title">On this page</p>
        <ul>${sections.map((m) => `
          <li><a href="#${m[1]}">${m[2]}</a></li>`).join('')}
        </ul>
      </nav>` : '';
  const i = STUDIES.indexOf(st);
  const more = STUDIES.filter((o) => o !== st).slice(0, 3);
  const researched = st.researched ? `
      <p class="legal-updated">Sources checked ${esc(st.researched)}</p>` : '';
  return pageShell({
    up: '../../', title: st.title, description: st.summary, path: `studies/${st.slug}/`, bodyClass: 'studies-page study-page',
    main: `    <article class="container legal study">
      <p class="drip-back-row"><a class="drip-back" href="../">${BACK}All studies</a></p>
      <p class="eyebrow">Study ${i + 1} of ${STUDIES.length}</p>
      <h1 class="drip-title">${esc(st.title)}</h1>${researched}${studyDraft()}
      <p class="legal-lead">${esc(st.summary)}</p>
      ${STUDY_NOTICE}${toc}
      <div class="legal-body study-body">
${st.body}
      </div>
      <section class="study-more" aria-labelledby="study-more-title">
        <h2 class="study-more__title" id="study-more-title">More studies</h2>
        ${studyCardsHTML(more, '../../')}
      </section>
    </article>`,
  });
}

// The page for an address that doesn't exist (GitHub Pages shows 404.html).
// Links work from any depth through <base>, from siteUrl.
function notFoundHTML() {
  const base = SITE_URL ? new URL(SITE_URL).pathname : '/';
  return pageShell({
    up: '', title: 'Page not found', description: "This page doesn't exist.", path: '404.html', bodyClass: 'legal-page not-found',
    main: `    <div class="container legal">
      <h1 class="drip-title">Page not found</h1>
      <p class="legal-lead">Sorry, there's no page at this address. It may have moved, or the link may be mistyped.</p>
      <p class="not-found__links"><a class="btn btn--primary" href="./">Go to the home page</a> <a class="btn btn--secondary" href="./#treatments">See all treatments</a></p>
    </div>`,
  }).replace('<head>\n', `<head>\n  <base href="${esc(base)}">\n`);
}

// The mini drawings for the Treatments menu, as one file of <symbol>s.
function iconFileSVG() {
  const used = [...new Set(DRIPS.map((d) => VISUALS[d.slug].art).filter(Boolean))];
  const symbols = used.map((id) => {
    const paths = LINE_ART[id].paths.map((p) => {
      const o = typeof p === 'string' ? { d: p } : p;
      const move = o.transform ? ` transform="${esc(o.transform)}"` : '';
      return o.fill ? `<path d="${esc(o.d)}"${move} fill="currentColor" stroke="none"/>` : `<path d="${esc(o.d)}"${move}/>`;
    }).join('');
    return `  <symbol id="art-${esc(id)}" viewBox="0 0 400 400">${paths}</symbol>`;
  }).join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg">
<!-- ${GENERATED} (from data/line-art.js): the Treatments menu's mini drawings -->
${symbols}
</svg>
`;
}

/* ---------- Write ---------- */

// data/menu.js for the home page.
write('data/menu.js', `/* ${GENERATED} */
window.MENU = ${JSON.stringify(MENU, null, 2)};

// Picture, tint and badge of every drip (from TREATMENTS in script.js, or
// NEW_PICTURES in the generator).
window.MENU_VISUALS = ${JSON.stringify(VISUALS, null, 2)};
`);

// data/book-list.js: the treatments the booking preview (booking.js) offers,
// on every page.
write('data/book-list.js', `/* ${GENERATED} */
window.BOOK_LIST = ${JSON.stringify({
  drips: MENU.drips.map((d) => ({ name: d.name, price: d.priceLabel })),
  standalone: (MENU.standalone?.priceTable?.rows || []).map(([name, price]) => ({ name, price })),
}, null, 2)};
`);

// Treatment pages: generated folders are replaced; anything else is left alone.
if (!CHECK_ONLY && existsSync(at('treatments'))) {
  for (const name of readdirSync(at('treatments'))) {
    const file = at(`treatments/${name}/index.html`);
    if (existsSync(file) && readFileSync(file, 'utf8').includes(GENERATED)) rmSync(at(`treatments/${name}`), { recursive: true });
  }
}
for (const drip of DRIPS) write(`treatments/${drip.slug}/index.html`, pageHTML(drip));

// The ingredient glossary.
if (GLOSSARY.length) write('ingredients/index.html', glossaryPageHTML());

// The policy pages, complaints and questions.
for (const name of LEGAL) write(`${name}/index.html`, legalPageHTML(name));

// The studies: generated folders are replaced; anything else is left alone.
if (!CHECK_ONLY && existsSync(at('studies'))) {
  for (const name of readdirSync(at('studies'))) {
    const file = at(`studies/${name}/index.html`);
    if (existsSync(file) && readFileSync(file, 'utf8').includes(GENERATED)) rmSync(at(`studies/${name}`), { recursive: true });
  }
}
write('studies/index.html', studiesIndexHTML());
for (const st of STUDIES) write(`studies/${st.slug}/index.html`, studyPageHTML(st));

// The page for missing addresses, the Treatments menu's drawings, and the
// files for search engines (a sitemap only once launched).
write('404.html', notFoundHTML());
if (USE_LINES) write(ICON_FILE, iconFileSVG());
const PAGES = ['', ...DRIPS.map((d) => `treatments/${d.slug}/`), 'ingredients/', ...LEGAL.map((n) => `${n}/`), 'studies/', ...STUDIES.map((st) => `studies/${st.slug}/`)];
write('robots.txt', isOn('launched')
  ? `User-agent: *\nAllow: /\n${SITE_URL ? `\nSitemap: ${SITE_URL}sitemap.xml\n` : ''}`
  : 'User-agent: *\nDisallow: /\n');
if (isOn('launched') && SITE_URL) {
  write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.map((path) => `  <url><loc>${esc(SITE_URL + path)}</loc></url>`).join('\n')}
</urlset>
`);
} else if (!CHECK_ONLY && existsSync(at('sitemap.xml'))) rmSync(at('sitemap.xml'));

// index.html: only its Book and contact links, the business details and the logo change.
if (INDEX !== read('index.html')) write('index.html', INDEX);

/* ---------- Check ---------- */

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'source', 'track', 'wbr']);
const BLOCK = /<\/?(p|div|li|br|tr|td|th|caption|summary|h[1-6])\b[^>]*>/gi;

const decode = (text) => text
  .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
  .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
  .replace(/&(amp|lt|gt|quot|apos|nbsp);/g, (_, n) => ({ amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' })[n]);
const collapse = (text) => String(text).replace(/\s+/g, ' ').trim();
const textOf = (html) => collapse(decode(html.replace(/<!--[\s\S]*?-->/g, '').replace(BLOCK, ' ').replace(/<[^>]+>/g, '')));

// Every element with data-verbatim, and the text it shows.
function verbatimElements(html) {
  const found = [];
  const stack = [];
  const tagRe = /<!--[\s\S]*?-->|<(\/?)([a-zA-Z][a-zA-Z0-9-]*)((?:[^>"']|"[^"]*"|'[^']*')*)>/g;
  let m;
  while ((m = tagRe.exec(html))) {
    if (m[0].startsWith('<!--')) continue;
    const [, closing, rawTag, attrs] = m;
    const tag = rawTag.toLowerCase();
    if (VOID.has(tag) || attrs.trim().endsWith('/')) continue;
    if (!closing && (tag === 'script' || tag === 'style')) {
      const end = html.indexOf(`</${tag}`, tagRe.lastIndex);
      tagRe.lastIndex = end < 0 ? html.length : end;
      continue;
    }
    if (!closing) {
      const path = attrs.match(/\sdata-verbatim="([^"]*)"/);
      const part = attrs.match(/\sdata-verbatim-part="([^"]*)"/);
      stack.push({ tag, path: path ? decode(path[1]) : null, part: part ? part[1] : null, start: tagRe.lastIndex });
      continue;
    }
    let i = stack.length - 1;
    while (i >= 0 && stack[i].tag !== tag) i--;
    if (i < 0) continue;
    const el = stack[i];
    stack.length = i;
    if (el.path !== null) found.push({ path: el.path, part: el.part, text: textOf(html.slice(el.start, m.index)) });
  }
  return found;
}

// A path like "drips.iron-infusion.sections.2.body" (drips are found by slug).
function resolve(path) {
  let value = MENU;
  const keys = path.split('.');
  for (let i = 0; i < keys.length; i++) {
    if (value == null) return undefined;
    value = keys[i - 1] === 'drips' && i === 1 ? value.find((d) => d.slug === keys[i]) : value[keys[i]];
  }
  return value;
}

// The strings a treatment page must show.
function requiredFor(drip) {
  const p = `drips.${drip.slug}`;
  const paths = [`${p}.name`, `${p}.priceLabel`, `${p}.description`, 'disclaimer'];
  if (drip.tagline) paths.push(`${p}.tagline`);
  drip.ingredients.forEach((_, i) => paths.push(`${p}.ingredients.${i}`));
  drip.ingredientDescriptions.forEach((_, i) => paths.push(`${p}.ingredientDescriptions.${i}.name`, `${p}.ingredientDescriptions.${i}.text`));
  if (drip.priceTableLabel) paths.push(`${p}.priceTableLabel`);
  if (drip.priceTable) {
    drip.priceTable.columns.forEach((_, i) => paths.push(`${p}.priceTable.columns.${i}`));
    drip.priceTable.rows.forEach((row, r) => row.forEach((_, c) => paths.push(`${p}.priceTable.rows.${r}.${c}`)));
  }
  if (drip.moreInfoIntro) paths.push(`${p}.moreInfoIntro`);
  (drip.sections || []).forEach((_, i) => paths.push(`${p}.sections.${i}.heading`, `${p}.sections.${i}.body`));
  if (drip.pricingNote) paths.push(`${p}.pricingNote`);
  (drip.footnotes || []).forEach((_, i) => paths.push(`${p}.footnotes.${i}`));
  const other = drip.proVariantSlug || drip.baseVariantSlug;
  if (other) paths.push(`drips.${other}.name`, `drips.${other}.priceLabel`);
  if (drip.proVariantSlug) proAdds(drip, bySlug[drip.proVariantSlug]).adds.forEach((a) => paths.push(`drips.${drip.proVariantSlug}.ingredients.${a.i}`));
  return paths;
}

// The strings the glossary must show: every category, entry name and text.
function requiredForGlossary() {
  return ['disclaimer', ...GLOSSARY.flatMap((c) => [`${c.path}.category`, ...c.items.flatMap((item) => [`${item.path}.name`, `${item.path}.text`])])];
}

// The strings the home page must show once script.js has rendered it.
function requiredForHome() {
  const paths = [];
  // Every standard drip's card (a Pro version has no card: its standard
  // version's card links to it, which the home page check confirms).
  DRIPS.filter((d) => !d.baseVariantSlug).forEach((d) => paths.push(`drips.${d.slug}.name`, `drips.${d.slug}.priceLabel`));
  const s = MENU.standalone;
  paths.push('standalone.heading', 'standalone.intro');
  s.priceTable.columns.forEach((_, i) => paths.push(`standalone.priceTable.columns.${i}`));
  s.priceTable.rows.forEach((row, r) => row.forEach((_, c) => paths.push(`standalone.priceTable.rows.${r}.${c}`)));
  s.ingredientDescriptions.forEach((_, i) => paths.push(`standalone.ingredientDescriptions.${i}.name`, `standalone.ingredientDescriptions.${i}.text`));
  return paths;
}

// Compares every data-verbatim element with the JSON and confirms every
// required string is shown. Returns the problems found.
function checkStrings(html, required) {
  const problems = [];
  const found = verbatimElements(html);
  for (const { path, part, text } of found) {
    const value = resolve(path);
    if (typeof value !== 'string') problems.push(`${path}: not a string in data/drips.json`);
    // data-verbatim-part="start": the opening sentences of the string, word for word.
    else if (part === 'start') {
      if (!text || !collapse(value).startsWith(text) || !(text === collapse(value) || /[.!?]\d*$/.test(text))) {
        problems.push(`${path}: shows "${text.slice(0, 80)}…", which isn't the string's opening sentences`);
      }
    } else if (text !== collapse(value)) problems.push(`${path}: shows "${text.slice(0, 80)}…", expected "${collapse(value).slice(0, 80)}…"`);
  }
  const shown = new Set(found.map((f) => f.path));
  for (const path of required) if (!shown.has(path)) problems.push(`${path}: not shown`);
  return { problems, count: found.length };
}

// Structure: title, robots, one h1, no skipped heading levels, no raw prices in pence.
function checkPage(html, drip, expectedTitle = `${drip.name} | ${SITE_NAME}`) {
  const problems = [];
  const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1];
  if (decode(title || '') !== expectedTitle) problems.push(`title is "${title}"`);
  if (html.includes('<meta name="robots" content="noindex, nofollow">') === isOn('launched')) problems.push(isOn('launched') ? 'still asks search engines not to list it (launched is true)' : 'robots meta missing (launched is false)');
  const levels = [...html.matchAll(/<h([1-6])\b/g)].map((m) => Number(m[1]));
  if (levels.filter((l) => l === 1).length !== 1) problems.push(`${levels.filter((l) => l === 1).length} h1 elements`);
  levels.forEach((l, i) => { if (i && l > levels[i - 1] + 1) problems.push(`heading level skips from h${levels[i - 1]} to h${l}`); });
  if (drip.priceFromPence != null && html.includes(String(drip.priceFromPence))) problems.push('shows priceFromPence');
  const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  const twice = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (twice.length) problems.push(`ids used twice: ${[...new Set(twice)].join(', ')}`);
  return problems;
}

const lines = [];
let failures = 0;
const report = (ok, label, detail, problems = []) => {
  if (!ok) failures++;
  lines.push(`${ok ? 'PASS' : 'FAIL'}  ${label.padEnd(44)} ${detail}`);
  problems.forEach((p) => lines.push(`        - ${p}`));
};

for (const drip of DRIPS) {
  const html = read(`treatments/${drip.slug}/index.html`);
  const { problems, count } = checkStrings(html, requiredFor(drip));
  problems.push(...checkPage(html, drip));
  report(!problems.length, `treatments/${drip.slug}/`, `${count} strings`, problems);
}

if (GLOSSARY.length) {
  const html = read('ingredients/index.html');
  const { problems, count } = checkStrings(html, requiredForGlossary());
  problems.push(...checkPage(html, {}, `${GLOSSARY_TITLE} | ${SITE_NAME}`));
  report(!problems.length, 'ingredients/ (glossary)', `${count} strings`, problems);
}

for (const name of LEGAL) {
  const html = read(`${name}/index.html`);
  const problems = checkPage(html, {}, `${legalSource(name).title} | ${SITE_NAME}`);
  if (/\{\{|\[\[/.test(html)) problems.push('a {{value}} or [[gap]] was left unfilled');
  if (html !== legalPageHTML(name)) problems.push('out of date: run node scripts/build-menu.mjs');
  const gaps = (html.match(/class="legal-gap"/g) || []).length;
  report(!problems.length, `${name}/ (policy)`, gaps ? `${gaps} gaps for the clinic to fill in` : 'complete', problems);
}

// The studies: up to date, every citation points at a source, every source is cited.
{
  const check = (file, expected, extra = []) => {
    const html = existsSync(at(file)) ? read(file) : '';
    const problems = [...extra];
    if (html !== expected) problems.push('out of date: run node scripts/build-menu.mjs');
    return problems;
  };
  report(!check('studies/index.html', studiesIndexHTML()).length, 'studies/ (all studies)', `${STUDIES.length} studies`, check('studies/index.html', studiesIndexHTML()));
  for (const st of STUDIES) {
    const cited = new Set([...st.body.matchAll(/href="#source-(\d+)"/g)].map((m) => m[1]));
    const listed = new Set([...st.body.matchAll(/<li id="source-(\d+)"/g)].map((m) => m[1]));
    const extra = [];
    for (const n of cited) if (!listed.has(n)) extra.push(`cites source ${n}, which isn't in its list`);
    for (const n of listed) if (!cited.has(n)) extra.push(`lists source ${n}, which it never cites`);
    if (!listed.size) extra.push('has no sources');
    const problems = check(`studies/${st.slug}/index.html`, studyPageHTML(st), extra);
    report(!problems.length, `studies/${st.slug}/`, `${listed.size} sources`, problems);
  }
  const p404 = check('404.html', notFoundHTML());
  report(!p404.length, '404.html (page not found)', SITE_URL ? `links from ${new URL(SITE_URL).pathname}` : 'links from /', p404);
  if (USE_LINES) {
    const pIcons = check(ICON_FILE, iconFileSVG());
    report(!pIcons.length, `${ICON_FILE} (the menu's drawings)`, `${(iconFileSVG().match(/<symbol /g) || []).length} drawings`, pIcons);
  }
}

/* The home page is built by script.js, so it is checked as script.js renders
   it: site-config.js, data/line-art.js, data/menu.js and script.js run here
   with a minimal stand-in for the page (no browser needed), and the HTML
   they insert is checked the same way. */

function renderedHome() {
  const noop = () => {};
  const roots = {};
  const ROOTS = ['stage-root', 'treatment-grid', 'standalone-root'];
  const classList = { add: noop, remove: noop, toggle: noop };
  const document = {
    getElementById: (id) => (ROOTS.includes(id) ? (roots[id] ||= { innerHTML: '', querySelectorAll: () => [] }) : null),
    querySelectorAll: () => [],
    addEventListener: noop,
    documentElement: { classList },
  };
  const window = { addEventListener: noop, matchMedia: () => ({ matches: false, addEventListener: noop }) };
  const context = vm.createContext({ window, document, location: { hash: '' }, history: { pushState: noop }, console });
  // The page's own settings and drawings first, as index.html loads them.
  vm.runInContext(read('site-config.js'), context, { filename: 'site-config.js', timeout: 5000 });
  if (existsSync(at('data/line-art.js'))) vm.runInContext(read('data/line-art.js'), context, { filename: 'data/line-art.js', timeout: 5000 });
  vm.runInContext(read('data/menu.js'), context, { filename: 'data/menu.js', timeout: 5000 });
  vm.runInContext(read('script.js'), context, { filename: 'script.js', timeout: 5000 });
  // render() writes the featured treatments' sections, the cards and the
  // standalone section; everything that follows only adds behaviour.
  return ROOTS.map((id) => roots[id]?.innerHTML || '').join('\n');
}

{
  const label = 'index.html (home page, as script.js renders it)';
  try {
    const html = renderedHome();
    const { problems, count } = checkStrings(html, requiredForHome());
    if (/\bFrom\s*£/.test(textOf(html))) problems.push('a price still has "From" in front of it');
    if (!/<details[^>]*\sid="vitamin-d"/.test(html)) problems.push('no #vitamin-d entry in the standalone section');
    for (const d of DRIPS.filter((x) => x.baseVariantSlug)) {
      if (!html.includes(`class="pro-chip card__upgrade" href="treatments/${d.slug}/"`)) problems.push(`${d.slug}: no "Upgrade to Pro" link to it on its standard version's card`);
      if (html.includes(`class="card__link" href="treatments/${d.slug}/"`)) problems.push(`${d.slug}: has a card of its own (Pro versions are reached by "Upgrade to Pro")`);
    }
    report(!problems.length, label, `${count} strings`, problems);
  } catch (error) {
    report(false, label, 'could not render', [error.message]);
  }
}

// Where the menu itself says "Blue Bird Wellness" (the site's own name is SITE_NAME).
function findText(value, needle, path = '') {
  if (typeof value === 'string') return value.includes(needle) ? [path] : [];
  if (Array.isArray(value)) return value.flatMap((v, i) => findText(v, needle, `${path}.${value[i]?.slug || i}`));
  if (value && typeof value === 'object') return Object.entries(value).flatMap(([k, v]) => findText(v, needle, path ? `${path}.${k}` : k));
  return [];
}
const brand = findText(MENU, 'Blue Bird Wellness');

// How the ingredients matched up.
const matching = [];
for (const drip of DRIPS) {
  const { rows, notes, unmatched } = ingredientRows(drip);
  const all = rows.flatMap((r) => [r, ...r.children]);
  const plain = all.filter((r) => !r.desc).map((r) => r.line);
  if (unmatched.length) matching.push(`${drip.slug}: description(s) matching no ingredient line, shown at the end of its list: ${unmatched.map((d) => `"${d.name}"`).join(', ')}`);
  if (notes.length) matching.push(`${drip.slug}: shown as small print under the list: ${notes.map((n) => `"${n.line}"`).join(', ')}`);
  const grouped = rows.flatMap((r) => r.children.map((c) => c.line));
  const loose = plain.filter((line) => !grouped.includes(line));
  if (loose.length) matching.push(`${drip.slug}: line(s) with no description: ${loose.map((l) => `"${l}"`).join(', ')}`);
  const noEntry = drip.ingredientDescriptions.filter((d) => !glossaryFor(d.name)).map((d) => `"${d.name}"`);
  if (noEntry.length) matching.push(`${drip.slug}: description(s) with no glossary entry (no glossary link): ${noEntry.join(', ')}`);
}
const lonely = GLOSSARY_ITEMS.filter((item) => { const u = usedIn(item); return !u.drips.length && !u.standalone; });
matching.push(lonely.length
  ? `Glossary entries used by no drip and no standalone booster: ${lonely.map((i) => `"${i.name}"`).join(', ')}`
  : 'Every glossary entry is used by at least one drip or standalone booster.');
const standaloneOnly = GLOSSARY_ITEMS.filter((item) => { const u = usedIn(item); return !u.drips.length && u.standalone; });
if (standaloneOnly.length) matching.push(`Glossary entries used only as standalone boosters: ${standaloneOnly.map((i) => `"${i.name}"`).join(', ')}`);
const upgrades = DRIPS.filter((d) => d.proVariantSlug).map((d) => {
  const pro = bySlug[d.proVariantSlug];
  const { adds, medicines } = proAdds(d, pro);
  return `${pro.slug} adds: ${adds.map((a) => `"${a.line}"`).join(', ') || '(nothing)'}${medicines.length ? `; medicines left out: ${medicines.map((m) => `"${m.line}"`).join(', ')}` : ''}`;
});

const out = [
  `Menu check: data/drips.json (${DRIPS.length} drips) against the generated pages and the home page.`,
  'Every string marked data-verbatim must equal data/drips.json (whitespace collapsed), and every required string must be shown.',
  '',
  ...lines,
  '',
  failures ? `Result: ${failures} FAILED` : 'Result: all passed',
  '',
  'Notes',
  ...(notes.length ? notes.map((n) => `  - ${n}`) : ['  - none']),
  '',
  `"Blue Bird Wellness" in the menu (shown as written wherever the page shows that string):`,
  ...brand.map((p) => `  - ${p}`),
  '',
  'Ingredients (lines, descriptions and glossary entries matched by name, before any "(" or ",", ignoring case and "L-")',
  ...matching.map((m) => `  - ${m}`),
  '',
  '"Upgrade to Pro" cards ("Pro adds": lines the standard drip does not have, never medicines)',
  ...upgrades.map((u) => `  - ${u}`),
  '',
].join('\n');

if (!CHECK_ONLY) write('data/menu-check.txt', out);
console.log(out);
process.exit(failures ? 1 : 0);
