#!/usr/bin/env node
/* ==========================================================================
   Bluebird Wellness: menu generator

   Reads the clinic's menu, data/drips.json, and writes:
     data/menu.js                  window.MENU (the JSON as it is), the
                                   picture/tint/badge of every drip and
                                   BOOK_URL, for the home page (script.js)
     treatments/<slug>/index.html  one static page per drip, with all its
                                   text in the HTML
     index.html                    only the href of every data-book link
     data/menu-check.txt           the check report (also printed)

   Run it after editing data/drips.json, BOOK_URL below, or a treatment's
   image, alt, tint or badge in TREATMENTS (script.js), then commit what it
   writes:
     node scripts/build-menu.mjs
   To check the files as they are, without writing anything:
     node scripts/build-menu.mjs --check

   Rule zero: every treatment string is shown exactly as it is in
   data/drips.json, escaped as text. Elements that show one carry
   data-verbatim with its path in the JSON; the check compares each of them
   with the JSON and confirms nothing is missing.
   ========================================================================== */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

/* ---------- Settings ---------- */

// Where every "Book" and "Book now" button goes, on the home page and on every
// treatment page. "#" until the booking system exists.
const BOOK_URL = '#';

// The brand name in page titles, headers and footers (the menu text itself
// stays exactly as written).
const SITE_NAME = 'Bluebird Wellness';

// Drips with no picture on the stage. Until images/treatments/<slug>.webp
// exists they show a soft placeholder shape; when it does, it is used
// instead (fill in its alt: a plain description of the picture, no claims).
const NEW_PICTURES = {
  'myers-cocktail-infusion': { placeholder: { shape: 'drop', colour: '#E8EFFB' }, alt: '' },
  'signature-infusion': { placeholder: { shape: 'blob', colour: '#E8EFFB' }, alt: '' },
};

const GENERATED = 'Generated by scripts/build-menu.mjs from data/drips.json. Don\'t edit by hand.';

/* ---------- Files ---------- */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');
const at = (file) => join(ROOT, file);
const read = (file) => readFileSync(at(file), 'utf8');
const write = (file, text) => {
  if (CHECK_ONLY) return;
  mkdirSync(dirname(at(file)), { recursive: true });
  writeFileSync(at(file), text);
};
const fail = (message) => {
  console.error(`\nbuild-menu: ${message}\n`);
  process.exit(1);
};

const notes = [];

/* ---------- The menu ---------- */

const MENU = JSON.parse(read('data/drips.json'));
const DRIPS = MENU.drips;
if (!Array.isArray(DRIPS) || !DRIPS.length) fail('data/drips.json has no drips.');
for (const drip of DRIPS) {
  for (const key of ['slug', 'name', 'priceLabel', 'description', 'ingredients', 'ingredientDescriptions']) {
    if (drip[key] == null) fail(`${drip.slug || '(no slug)'} has no ${key}.`);
  }
}
const bySlug = Object.fromEntries(DRIPS.map((d) => [d.slug, d]));

/* ---------- The stage's visuals (TREATMENTS in script.js) ---------- */

// TREATMENTS is a plain array literal, so it can be read here without
// running the rest of script.js.
function readTreatments() {
  const src = read('script.js');
  const start = src.indexOf('const TREATMENTS = [');
  const end = src.indexOf('\n];', start);
  if (start < 0 || end < 0) fail('Could not find "const TREATMENTS = [ … ];" in script.js.');
  try {
    return vm.runInNewContext(`(${src.slice(src.indexOf('[', start), end + 2)})`, {}, { timeout: 1000 });
  } catch (error) {
    fail(`Could not read TREATMENTS in script.js: ${error.message}`);
  }
}
const TREATMENTS = readTreatments();

// Width and height of a WebP file, from its header.
function webpSize(file) {
  const b = readFileSync(at(file));
  if (b.toString('ascii', 0, 4) !== 'RIFF' || b.toString('ascii', 8, 12) !== 'WEBP') return null;
  const chunk = b.toString('ascii', 12, 16);
  if (chunk === 'VP8X') return [1 + b.readUIntLE(24, 3), 1 + b.readUIntLE(27, 3)];
  if (chunk === 'VP8 ') return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
  if (chunk === 'VP8L') {
    const n = b.readUInt32LE(21);
    return [1 + (n & 0x3fff), 1 + ((n >> 14) & 0x3fff)];
  }
  return null;
}

function checkedSize(file, declared) {
  if (!existsSync(at(file))) fail(`Missing image: ${file}`);
  const size = webpSize(file);
  if (!size) return declared;
  if (declared && (declared[0] !== size[0] || declared[1] !== size[1])) {
    notes.push(`${file} is ${size[0]} × ${size[1]}, but TREATMENTS says ${declared[0]} × ${declared[1]}; the pages use the file's size.`);
  }
  return size;
}

// The picture, tint and badge of a drip: its own stage treatment's, or (for a
// Pro drip) its standard version's, or a new picture/placeholder.
function visualsFor(drip) {
  const own = TREATMENTS.find((t) => t.menuSlug === drip.slug);
  const stage = own || (drip.baseVariantSlug && TREATMENTS.find((t) => t.menuSlug === drip.baseVariantSlug));
  if (stage) {
    if (!stage.image) fail(`TREATMENTS entry "${stage.id}" has no image.`);
    return {
      image: stage.image,
      imageSize: checkedSize(stage.image, stage.imageSize),
      imageFit: stage.imageFit || null,
      alt: stage.alt || '',
      tint: stage.showcase?.tint || null,
      badge: own?.badge || null,
    };
  }
  const extra = NEW_PICTURES[drip.slug];
  if (!extra) fail(`No picture for ${drip.slug}: link it to a TREATMENTS entry (menuSlug) or add it to NEW_PICTURES.`);
  const future = `images/treatments/${drip.slug}.webp`;
  if (existsSync(at(future))) {
    if (!extra.alt) notes.push(`${future} has no alt text yet: add it to NEW_PICTURES in scripts/build-menu.mjs.`);
    return { image: future, imageSize: checkedSize(future, null), imageFit: null, alt: extra.alt || '', tint: null, badge: null };
  }
  return { image: null, placeholder: extra.placeholder, tint: null, badge: null };
}

const VISUALS = Object.fromEntries(DRIPS.map((d) => [d.slug, visualsFor(d)]));

for (const t of TREATMENTS) {
  if (t.menuSlug && !bySlug[t.menuSlug]) fail(`TREATMENTS entry "${t.id}" links to "${t.menuSlug}", which isn't on the menu.`);
  if (t.standalone && !MENU.standalone?.priceTable.rows.some((row) => row[0] === t.standalone.row)) {
    fail(`TREATMENTS entry "${t.id}" links to the standalone row "${t.standalone.row}", which isn't on the menu.`);
  }
  if (t.standalone && !MENU.standalone.ingredientDescriptions.some((d) => d.name === t.standalone.entry)) {
    fail(`TREATMENTS entry "${t.id}" links to the standalone entry "${t.standalone.entry}", which isn't on the menu.`);
  }
}

/* ---------- HTML helpers ---------- */

const esc = (value) =>
  String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);

// data-verbatim: the path of the string in data/drips.json.
const vb = (path) => ` data-verbatim="${esc(path)}"`;

// "\n\n" in a menu string is a paragraph break.
const paras = (text, indent = '') => String(text).split('\n\n').map((p) => `${indent}<p>${esc(p)}</p>`).join('\n');

// An HTML comment can't contain "--".
const commentText = (text) => String(text).replace(/--/g, '- -');

const slugify = (text) => String(text).toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* ---------- Header and footer: the home page's, pointed back at it ---------- */

const INDEX = read('index.html');

function slice(html, open, close) {
  const start = html.indexOf(open);
  const end = html.indexOf(close, start);
  if (start < 0 || end < 0) fail(`Could not find ${open} … ${close} in index.html.`);
  return html.slice(start, end + close.length);
}

// data-book links go to BOOK_URL; in-page links go back to the home page.
const withBookUrl = (html) =>
  html.replace(/<a\b[^>]*\bdata-book\b[^>]*>/g, (tag) => tag.replace(/\shref="[^"]*"/, ` href="${esc(BOOK_URL)}"`));
const rebase = (html) =>
  withBookUrl(html)
    .replace(/href="#top"/g, 'href="../../"')
    .replace(/href="#([A-Za-z][^"]*)"/g, 'href="../../#$1"');

const HEADER = rebase(slice(INDEX, '<header class="site-header"', '</header>'));
const FOOTER = rebase(slice(INDEX, '<footer class="site-footer">', '</footer>'));
const ICON = (INDEX.match(/<link rel="icon"[^>]*>/) || [''])[0];

/* ---------- Treatment page ---------- */

function pictureHTML(drip, v) {
  if (!v.image) {
    return `<div class="drip-picture drip-picture--placeholder" data-reveal-load>
            <!-- No picture yet. Save it as images/treatments/${drip.slug}.webp and run the generator.
                 imageBrief: ${commentText(drip.imageBrief || '')} -->
            <span class="placeholder placeholder--${esc(v.placeholder.shape)}" style="--ph: ${esc(v.placeholder.colour)}" aria-hidden="true"></span>
          </div>`;
  }
  const [w, h] = v.imageSize;
  const cls = v.imageFit === 'cover' ? 'drip-picture drip-picture--photo' : 'drip-picture';
  return `<div class="${cls}" data-reveal-load>
            <img src="../../${esc(v.image)}" alt="${esc(v.alt)}" width="${w}" height="${h}" fetchpriority="high" decoding="async">
          </div>`;
}

const ARROW = '<svg class="variant-link__icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h10M9 4l4 4-4 4"/></svg>';
const BACK = '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M13 8H3M7 4 3 8l4 4"/></svg>';

// The quiet link between a drip and its Pro (or standard) version.
function variantHTML(drip) {
  const other = bySlug[drip.proVariantSlug || drip.baseVariantSlug];
  if (!other) return '';
  return `
          <p class="drip-variant">
            <a class="variant-link" href="../${esc(other.slug)}/"><span${vb(`drips.${other.slug}.name`)}>${esc(other.name)}</span> <span class="variant-link__price"${vb(`drips.${other.slug}.priceLabel`)}>${esc(other.priceLabel)}</span>${ARROW}</a>
          </p>`;
}

function priceTableHTML(table, path, caption) {
  const head = table.columns.map((c, i) => `<th scope="col"${vb(`${path}.columns.${i}`)}>${esc(c)}</th>`).join('');
  const rows = table.rows.map((row, r) => {
    const cells = row.map((cell, c) => (c === 0
      ? `<th scope="row"${vb(`${path}.rows.${r}.${c}`)}>${esc(cell)}</th>`
      : `<td${vb(`${path}.rows.${r}.${c}`)}>${esc(cell)}</td>`)).join('');
    return `              <tr>${cells}</tr>`;
  }).join('\n');
  return `<table class="price-table">
              ${caption}
              <thead><tr>${head}</tr></thead>
              <tbody>
${rows}
              </tbody>
            </table>`;
}

function whatsInItHTML(drip, p) {
  if (!drip.ingredients.length && !drip.ingredientDescriptions.length) return '';
  const list = drip.ingredients.map((item, i) => `              <li${vb(`${p}.ingredients.${i}`)}>${esc(item)}</li>`).join('\n');
  const guide = drip.ingredientDescriptions.map((d, i) => `
              <details class="accordion__item">
                <summary class="accordion__summary"><span${vb(`${p}.ingredientDescriptions.${i}.name`)}>${esc(d.name)}</span></summary>
                <div class="accordion__body"${vb(`${p}.ingredientDescriptions.${i}.text`)}>
${paras(d.text, '                  ')}
                </div>
              </details>`).join('');
  const ingredients = drip.ingredients.length ? `
          <div class="drip-ingredients" data-fade>
            <h3 class="drip-subtitle">Ingredients</h3>
            <ul class="ingredient-list">
${list}
            </ul>
          </div>` : '';
  const guideBlock = drip.ingredientDescriptions.length ? `
          <div class="drip-guide" data-fade>
            <div class="drip-guide__head">
              <h3 class="drip-subtitle">Ingredient guide</h3>
              <button type="button" class="btn btn--secondary btn--compact" data-expand-all aria-controls="ingredient-guide" hidden>Expand all</button>
            </div>
            <div class="accordion" id="ingredient-guide">${guide}
            </div>
          </div>` : '';
  return `
    <section class="drip-section" aria-labelledby="whats-in-it">
      <div class="container">
        <h2 class="drip-section__title" id="whats-in-it" data-fade>What's in it</h2>
        <div class="drip-contents">${ingredients}${guideBlock}
        </div>
      </div>
    </section>`;
}

function pricesHTML(drip, p) {
  if (!drip.priceTable && !drip.pricingNote) return '';
  const note = drip.pricingNote ? `
        <div class="drip-prose" data-fade${vb(`${p}.pricingNote`)}>
${paras(drip.pricingNote, '          ')}
        </div>` : '';
  const caption = drip.priceTableLabel ? `<caption${vb(`${p}.priceTableLabel`)}>${esc(drip.priceTableLabel)}</caption>` : '';
  const table = drip.priceTable ? `
        <div class="price-table-wrap" data-fade>
          ${priceTableHTML(drip.priceTable, `${p}.priceTable`, caption)}
        </div>` : '';
  return `
    <section class="drip-section" aria-labelledby="prices">
      <div class="container">
        <h2 class="drip-section__title" id="prices" data-fade>Prices</h2>${note}${table}
      </div>
    </section>`;
}

// Iron's long read: the intro, a contents list and its sections.
function longFormHTML(drip, p) {
  if (!drip.sections?.length && !drip.moreInfoIntro) return '';
  const ids = (drip.sections || []).map((s) => slugify(s.heading));
  const intro = drip.moreInfoIntro ? `
        <div class="drip-prose drip-prose--lead" data-fade${vb(`${p}.moreInfoIntro`)}>
${paras(drip.moreInfoIntro, '          ')}
        </div>` : '';
  const toc = drip.sections?.length ? `
        <nav class="toc" aria-labelledby="contents-title" data-fade>
          <h2 class="toc__title" id="contents-title">Contents</h2>
          <ol class="toc__list">
${drip.sections.map((s, i) => `            <li><a class="link" href="#${ids[i]}"${vb(`${p}.sections.${i}.heading`)}>${esc(s.heading)}</a></li>`).join('\n')}
          </ol>
        </nav>` : '';
  const sections = (drip.sections || []).map((s, i) => `
        <section class="longform-section" id="${ids[i]}" aria-labelledby="${ids[i]}-title">
          <h2 class="drip-section__title" id="${ids[i]}-title" data-fade${vb(`${p}.sections.${i}.heading`)}>${esc(s.heading)}</h2>
          <div class="drip-prose" data-fade${vb(`${p}.sections.${i}.body`)}>
${paras(s.body, '            ')}
          </div>
        </section>`).join('');
  return `
    <div class="drip-longform">
      <div class="container">${intro}${toc}${sections}
      </div>
    </div>`;
}

function footnotesHTML(drip, p) {
  if (!drip.footnotes?.length) return '';
  const items = drip.footnotes.map((f, i) => {
    const n = (String(f).match(/^\d+/) || [String(i + 1)])[0];
    return `          <li id="footnote-${n}"${vb(`${p}.footnotes.${i}`)}>${esc(f)}</li>`;
  }).join('\n');
  return `
    <section class="drip-section drip-footnotes" aria-label="Footnotes">
      <div class="container">
        <ol class="footnotes">
${items}
        </ol>
      </div>
    </section>`;
}

function pageHTML(drip) {
  const p = `drips.${drip.slug}`;
  const v = VISUALS[drip.slug];
  const tint = v.tint || '#F7F4EF';
  const tagline = drip.tagline ? `
          <p class="drip-tagline"${vb(`${p}.tagline`)}>${esc(drip.tagline)}</p>` : '';
  const badge = v.badge ? `<span class="${v.badge.variant === 'sage' ? 'badge badge--sage' : 'badge'}">${esc(v.badge.text)}</span>` : '';

  return `<!DOCTYPE html>
<!-- ${GENERATED} -->
<html lang="en-GB" style="--page-tint: ${esc(tint)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(drip.name)} | ${esc(SITE_NAME)}</title>
  <meta name="theme-color" content="${esc(tint)}">
  <!-- Remove before launch, after the menu wording has had its compliance review -->
  <meta name="robots" content="noindex, nofollow">
  ${ICON}

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap">
  <link rel="stylesheet" href="../../styles.css">
</head>
<body class="drip-page">
  <a class="skip-link" href="#main">Skip to content</a>

  ${HEADER}

  <main id="main">
    <div class="drip-intro">
      <div class="container drip-intro__inner">
        <div class="drip-intro__text">
          <a class="drip-back" href="../../#treatments">${BACK}Back to all treatments</a>
          <h1 class="drip-title"${vb(`${p}.name`)}>${esc(drip.name)}</h1>${tagline}
          <div class="drip-meta">
            <p class="drip-price"${vb(`${p}.priceLabel`)}>${esc(drip.priceLabel)}</p>
            ${badge}
          </div>${variantHTML(drip)}
          <div class="drip-prose drip-description"${vb(`${p}.description`)}>
${paras(drip.description, '            ')}
          </div>
        </div>
        <div class="drip-intro__media">
          ${pictureHTML(drip, v)}
        </div>
      </div>
    </div>
${longFormHTML(drip, p)}${whatsInItHTML(drip, p)}${pricesHTML(drip, p)}${footnotesHTML(drip, p)}

    <section class="drip-book" aria-label="Book">
      <div class="container">
        <div class="drip-book__panel" data-fade>
          <a class="btn btn--primary" href="${esc(BOOK_URL)}" data-book>Book now<span class="visually-hidden"> ${esc(drip.name)}</span></a>
          <p class="drip-disclaimer"${vb('disclaimer')}>${esc(MENU.disclaimer)}</p>
          <a class="drip-back" href="../../#treatments">${BACK}Back to all treatments</a>
        </div>
      </div>
    </section>
  </main>

  ${FOOTER}

  <script src="../../treatment.js" defer></script>
</body>
</html>
`;
}

/* ---------- Write ---------- */

// data/menu.js for the home page.
write('data/menu.js', `/* ${GENERATED} */
window.MENU = ${JSON.stringify(MENU, null, 2)};

// Picture, tint and badge of every drip (from TREATMENTS in script.js, or
// NEW_PICTURES in the generator).
window.MENU_VISUALS = ${JSON.stringify(VISUALS, null, 2)};

// Where every Book button goes.
window.BOOK_URL = ${JSON.stringify(BOOK_URL)};
`);

// Treatment pages: generated folders are replaced; anything else is left alone.
if (!CHECK_ONLY && existsSync(at('treatments'))) {
  for (const name of readdirSync(at('treatments'))) {
    const file = at(`treatments/${name}/index.html`);
    if (existsSync(file) && readFileSync(file, 'utf8').includes(GENERATED)) rmSync(at(`treatments/${name}`), { recursive: true });
  }
}
for (const drip of DRIPS) write(`treatments/${drip.slug}/index.html`, pageHTML(drip));

// index.html: only the data-book links change.
const indexOut = withBookUrl(INDEX);
if (indexOut !== INDEX) write('index.html', indexOut);

/* ---------- Check ---------- */

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'source', 'track', 'wbr']);
const BLOCK = /<\/?(p|div|li|br|tr|td|th|caption|summary|h[1-6])\b[^>]*>/gi;

const decode = (text) => text
  .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
  .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
  .replace(/&(amp|lt|gt|quot|apos|nbsp);/g, (_, n) => ({ amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' })[n]);
const collapse = (text) => String(text).replace(/\s+/g, ' ').trim();
const textOf = (html) => collapse(decode(html.replace(/<!--[\s\S]*?-->/g, '').replace(BLOCK, ' ').replace(/<[^>]+>/g, '')));

// Every element with data-verbatim, and the text it shows.
function verbatimElements(html) {
  const found = [];
  const stack = [];
  const tagRe = /<!--[\s\S]*?-->|<(\/?)([a-zA-Z][a-zA-Z0-9-]*)((?:[^>"']|"[^"]*"|'[^']*')*)>/g;
  let m;
  while ((m = tagRe.exec(html))) {
    if (m[0].startsWith('<!--')) continue;
    const [, closing, rawTag, attrs] = m;
    const tag = rawTag.toLowerCase();
    if (VOID.has(tag) || attrs.trim().endsWith('/')) continue;
    if (!closing && (tag === 'script' || tag === 'style')) {
      const end = html.indexOf(`</${tag}`, tagRe.lastIndex);
      tagRe.lastIndex = end < 0 ? html.length : end;
      continue;
    }
    if (!closing) {
      const path = attrs.match(/\sdata-verbatim="([^"]*)"/);
      stack.push({ tag, path: path ? decode(path[1]) : null, start: tagRe.lastIndex });
      continue;
    }
    let i = stack.length - 1;
    while (i >= 0 && stack[i].tag !== tag) i--;
    if (i < 0) continue;
    const el = stack[i];
    stack.length = i;
    if (el.path !== null) found.push({ path: el.path, text: textOf(html.slice(el.start, m.index)) });
  }
  return found;
}

// A path like "drips.iron-infusion.sections.2.body" (drips are found by slug).
function resolve(path) {
  let value = MENU;
  const keys = path.split('.');
  for (let i = 0; i < keys.length; i++) {
    if (value == null) return undefined;
    value = keys[i - 1] === 'drips' && i === 1 ? value.find((d) => d.slug === keys[i]) : value[keys[i]];
  }
  return value;
}

// The strings a treatment page must show.
function requiredFor(drip) {
  const p = `drips.${drip.slug}`;
  const paths = [`${p}.name`, `${p}.priceLabel`, `${p}.description`, 'disclaimer'];
  if (drip.tagline) paths.push(`${p}.tagline`);
  drip.ingredients.forEach((_, i) => paths.push(`${p}.ingredients.${i}`));
  drip.ingredientDescriptions.forEach((_, i) => paths.push(`${p}.ingredientDescriptions.${i}.name`, `${p}.ingredientDescriptions.${i}.text`));
  if (drip.priceTableLabel) paths.push(`${p}.priceTableLabel`);
  if (drip.priceTable) {
    drip.priceTable.columns.forEach((_, i) => paths.push(`${p}.priceTable.columns.${i}`));
    drip.priceTable.rows.forEach((row, r) => row.forEach((_, c) => paths.push(`${p}.priceTable.rows.${r}.${c}`)));
  }
  if (drip.moreInfoIntro) paths.push(`${p}.moreInfoIntro`);
  (drip.sections || []).forEach((_, i) => paths.push(`${p}.sections.${i}.heading`, `${p}.sections.${i}.body`));
  if (drip.pricingNote) paths.push(`${p}.pricingNote`);
  (drip.footnotes || []).forEach((_, i) => paths.push(`${p}.footnotes.${i}`));
  const other = drip.proVariantSlug || drip.baseVariantSlug;
  if (other) paths.push(`drips.${other}.name`, `drips.${other}.priceLabel`);
  return paths;
}

// The strings the home page must show once script.js has rendered it.
function requiredForHome() {
  const paths = [];
  DRIPS.forEach((d) => paths.push(`drips.${d.slug}.name`, `drips.${d.slug}.priceLabel`));
  const s = MENU.standalone;
  paths.push('standalone.heading', 'standalone.intro');
  s.priceTable.columns.forEach((_, i) => paths.push(`standalone.priceTable.columns.${i}`));
  s.priceTable.rows.forEach((row, r) => row.forEach((_, c) => paths.push(`standalone.priceTable.rows.${r}.${c}`)));
  s.ingredientDescriptions.forEach((_, i) => paths.push(`standalone.ingredientDescriptions.${i}.name`, `standalone.ingredientDescriptions.${i}.text`));
  return paths;
}

// Compares every data-verbatim element with the JSON and confirms every
// required string is shown. Returns the problems found.
function checkStrings(html, required) {
  const problems = [];
  const found = verbatimElements(html);
  for (const { path, text } of found) {
    const value = resolve(path);
    if (typeof value !== 'string') problems.push(`${path}: not a string in data/drips.json`);
    else if (text !== collapse(value)) problems.push(`${path}: shows "${text.slice(0, 80)}…", expected "${collapse(value).slice(0, 80)}…"`);
  }
  const shown = new Set(found.map((f) => f.path));
  for (const path of required) if (!shown.has(path)) problems.push(`${path}: not shown`);
  return { problems, count: found.length };
}

// Structure: title, robots, one h1, no skipped heading levels, no raw prices in pence.
function checkPage(html, drip) {
  const problems = [];
  const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1];
  if (decode(title || '') !== `${drip.name} | ${SITE_NAME}`) problems.push(`title is "${title}"`);
  if (!html.includes('<meta name="robots" content="noindex, nofollow">')) problems.push('robots meta missing');
  const levels = [...html.matchAll(/<h([1-6])\b/g)].map((m) => Number(m[1]));
  if (levels.filter((l) => l === 1).length !== 1) problems.push(`${levels.filter((l) => l === 1).length} h1 elements`);
  levels.forEach((l, i) => { if (i && l > levels[i - 1] + 1) problems.push(`heading level skips from h${levels[i - 1]} to h${l}`); });
  if (drip.priceFromPence != null && html.includes(String(drip.priceFromPence))) problems.push('shows priceFromPence');
  return problems;
}

const lines = [];
let failures = 0;
const report = (ok, label, detail, problems = []) => {
  if (!ok) failures++;
  lines.push(`${ok ? 'PASS' : 'FAIL'}  ${label.padEnd(44)} ${detail}`);
  problems.forEach((p) => lines.push(`        - ${p}`));
};

for (const drip of DRIPS) {
  const html = read(`treatments/${drip.slug}/index.html`);
  const { problems, count } = checkStrings(html, requiredFor(drip));
  problems.push(...checkPage(html, drip));
  report(!problems.length, `treatments/${drip.slug}/`, `${count} strings`, problems);
}

/* The home page is built by script.js, so it is checked as script.js renders
   it: data/menu.js and script.js run here with a minimal stand-in for the
   page (no browser needed), and the HTML they insert is checked the same way. */

function renderedHome() {
  const noop = () => {};
  const roots = {};
  const ROOTS = ['stage-root', 'treatment-grid', 'standalone-root'];
  const classList = { add: noop, remove: noop, toggle: noop };
  const document = {
    getElementById: (id) => (ROOTS.includes(id) ? (roots[id] ||= { innerHTML: '' }) : null),
    querySelectorAll: () => [],
    addEventListener: noop,
    documentElement: { classList },
  };
  const window = { addEventListener: noop, matchMedia: () => ({ matches: false, addEventListener: noop }) };
  const context = vm.createContext({ window, document, location: { hash: '' }, history: { pushState: noop }, console });
  vm.runInContext(read('data/menu.js'), context, { filename: 'data/menu.js', timeout: 5000 });
  vm.runInContext(read('script.js'), context, { filename: 'script.js', timeout: 5000 });
  return ROOTS.map((id) => roots[id]?.innerHTML || '').join('\n');
}

{
  const label = 'index.html (home page, as script.js renders it)';
  try {
    const html = renderedHome();
    const { problems, count } = checkStrings(html, requiredForHome());
    if (/\bFrom\s*£/.test(textOf(html))) problems.push('a price still has "From" in front of it');
    if (!/<details[^>]*\sid="vitamin-d"/.test(html)) problems.push('no #vitamin-d entry in the standalone section');
    report(!problems.length, label, `${count} strings`, problems);
  } catch (error) {
    report(false, label, 'could not render', [error.message]);
  }
}

// Where the menu itself says "Blue Bird Wellness" (the site's own name is SITE_NAME).
function findText(value, needle, path = '') {
  if (typeof value === 'string') return value.includes(needle) ? [path] : [];
  if (Array.isArray(value)) return value.flatMap((v, i) => findText(v, needle, `${path}.${value[i]?.slug || i}`));
  if (value && typeof value === 'object') return Object.entries(value).flatMap(([k, v]) => findText(v, needle, path ? `${path}.${k}` : k));
  return [];
}
const brand = findText(MENU, 'Blue Bird Wellness');

const out = [
  `Menu check: data/drips.json (${DRIPS.length} drips) against the generated pages and the home page.`,
  'Every string marked data-verbatim must equal data/drips.json (whitespace collapsed), and every required string must be shown.',
  '',
  ...lines,
  '',
  failures ? `Result: ${failures} FAILED` : 'Result: all passed',
  '',
  'Notes',
  ...(notes.length ? notes.map((n) => `  - ${n}`) : ['  - none']),
  '',
  `"Blue Bird Wellness" in the menu (shown as written wherever the page shows that string):`,
  ...brand.map((p) => `  - ${p}`),
  '',
].join('\n');

if (!CHECK_ONLY) write('data/menu-check.txt', out);
console.log(out);
process.exit(failures ? 1 : 0);
